insert into estacion (modelo, capacidad) values ('S80', 1);
insert into estacion (modelo, capacidad) values ('Elise', 2);
insert into estacion (modelo, capacidad) values ('Colorado', 3);
insert into estacion (modelo, capacidad) values ('Golf', 4);
insert into estacion (modelo, capacidad) values ('600SEC', 5);
insert into estacion (modelo, capacidad) values ('Regal', 6);
insert into estacion (modelo, capacidad) values ('Sonoma Club', 7);
insert into estacion (modelo, capacidad) values ('900', 8);
insert into estacion (modelo, capacidad) values ('SL-Class', 9);
insert into estacion (modelo, capacidad) values ('Cougar', 10);
insert into estacion (modelo, capacidad) values ('Caprice', 11);
insert into estacion (modelo, capacidad) values ('Boxster', 12);
insert into estacion (modelo, capacidad) values ('X5', 13);
insert into estacion (modelo, capacidad) values ('NSX', 14);
insert into estacion (modelo, capacidad) values ('Camry', 15);
insert into estacion (modelo, capacidad) values ('Sierra 1500', 16);
insert into estacion (modelo, capacidad) values ('300', 17);
insert into estacion (modelo, capacidad) values ('Expedition', 18);
insert into estacion (modelo, capacidad) values ('Mirage', 19);
insert into estacion (modelo, capacidad) values ('940', 20);
insert into estacion (modelo, capacidad) values ('Daewoo Magnus', 21);
insert into estacion (modelo, capacidad) values ('Mariner', 22);
insert into estacion (modelo, capacidad) values ('RX-8', 23);
insert into estacion (modelo, capacidad) values ('Bel Air', 24);
insert into estacion (modelo, capacidad) values ('1500', 25);
insert into estacion (modelo, capacidad) values ('F-Series', 26);
insert into estacion (modelo, capacidad) values ('LR3', 27);
insert into estacion (modelo, capacidad) values ('Montero', 28);
insert into estacion (modelo, capacidad) values ('Yukon', 29);
insert into estacion (modelo, capacidad) values ('Trans Sport', 30);
insert into estacion (modelo, capacidad) values ('XG350', 31);
insert into estacion (modelo, capacidad) values ('Corvette', 32);
insert into estacion (modelo, capacidad) values ('Supra', 33);
insert into estacion (modelo, capacidad) values ('Impreza', 34);
insert into estacion (modelo, capacidad) values ('Sequoia', 35);
insert into estacion (modelo, capacidad) values ('LS', 36);
insert into estacion (modelo, capacidad) values ('Avanti', 37);
insert into estacion (modelo, capacidad) values ('Pajero', 38);
insert into estacion (modelo, capacidad) values ('Sorento', 39);
insert into estacion (modelo, capacidad) values ('Esprit', 40);
insert into estacion (modelo, capacidad) values ('Suburban 1500', 41);
insert into estacion (modelo, capacidad) values ('I', 42);
insert into estacion (modelo, capacidad) values ('MR2', 43);
insert into estacion (modelo, capacidad) values ('Accent', 44);
insert into estacion (modelo, capacidad) values ('Truck', 45);
insert into estacion (modelo, capacidad) values ('G-Series 2500', 46);
insert into estacion (modelo, capacidad) values ('Savana 1500', 47);
insert into estacion (modelo, capacidad) values ('Optima', 48);
insert into estacion (modelo, capacidad) values ('Xterra', 49);
insert into estacion (modelo, capacidad) values ('SC', 50);
insert into estacion (modelo, capacidad) values ('3 Series', 51);
insert into estacion (modelo, capacidad) values ('Discovery', 52);
insert into estacion (modelo, capacidad) values ('Tahoe', 53);
insert into estacion (modelo, capacidad) values ('LeMans', 54);
insert into estacion (modelo, capacidad) values ('Sentra', 55);
insert into estacion (modelo, capacidad) values ('Oasis', 56);
insert into estacion (modelo, capacidad) values ('Escalade', 57);
insert into estacion (modelo, capacidad) values ('Sierra 3500', 58);
insert into estacion (modelo, capacidad) values ('Rio', 59);
insert into estacion (modelo, capacidad) values ('Matrix', 60);
insert into estacion (modelo, capacidad) values ('Safari', 61);
insert into estacion (modelo, capacidad) values ('200', 62);
insert into estacion (modelo, capacidad) values ('Outlander', 63);
insert into estacion (modelo, capacidad) values ('Navigator', 64);
insert into estacion (modelo, capacidad) values ('S10 Blazer', 65);
insert into estacion (modelo, capacidad) values ('Mazda6', 66);
insert into estacion (modelo, capacidad) values ('Sprinter', 67);
insert into estacion (modelo, capacidad) values ('Savana 1500', 68);
insert into estacion (modelo, capacidad) values ('Grand Prix', 69);
insert into estacion (modelo, capacidad) values ('Sonata', 70);
insert into estacion (modelo, capacidad) values ('DTS', 71);
insert into estacion (modelo, capacidad) values ('Malibu', 72);
insert into estacion (modelo, capacidad) values ('Quattroporte', 73);
insert into estacion (modelo, capacidad) values ('Traverse', 74);
insert into estacion (modelo, capacidad) values ('Ranger', 75);
insert into estacion (modelo, capacidad) values ('Grand Vitara', 76);
insert into estacion (modelo, capacidad) values ('MR2', 77);
insert into estacion (modelo, capacidad) values ('Z4 M', 78);
insert into estacion (modelo, capacidad) values ('Azure', 79);
insert into estacion (modelo, capacidad) values ('Santa Fe', 80);
insert into estacion (modelo, capacidad) values ('Blazer', 81);
insert into estacion (modelo, capacidad) values ('Corvette', 82);
insert into estacion (modelo, capacidad) values ('Expedition EL', 83);
insert into estacion (modelo, capacidad) values ('Impreza', 84);
insert into estacion (modelo, capacidad) values ('Probe', 85);
insert into estacion (modelo, capacidad) values ('Discovery', 86);
insert into estacion (modelo, capacidad) values ('Elise', 87);
insert into estacion (modelo, capacidad) values ('Taurus', 88);
insert into estacion (modelo, capacidad) values ('Aero 8', 89);
insert into estacion (modelo, capacidad) values ('Colorado', 90);
insert into estacion (modelo, capacidad) values ('Galant', 91);
insert into estacion (modelo, capacidad) values ('Regal', 92);
insert into estacion (modelo, capacidad) values ('Explorer Sport Trac', 93);
insert into estacion (modelo, capacidad) values ('B-Series Plus', 94);
insert into estacion (modelo, capacidad) values ('Town & Country', 95);
insert into estacion (modelo, capacidad) values ('Corvette', 96);
insert into estacion (modelo, capacidad) values ('300D', 97);
insert into estacion (modelo, capacidad) values ('G', 98);
insert into estacion (modelo, capacidad) values ('Q', 99);
insert into estacion (modelo, capacidad) values ('Monte Carlo', 100);
insert into estacion (modelo, capacidad) values ('Wrangler', 101);
insert into estacion (modelo, capacidad) values ('Avalanche 1500', 102);
insert into estacion (modelo, capacidad) values ('Jimmy', 103);
insert into estacion (modelo, capacidad) values ('Yukon', 104);
insert into estacion (modelo, capacidad) values ('Corvette', 105);
insert into estacion (modelo, capacidad) values ('Villager', 106);
insert into estacion (modelo, capacidad) values ('Explorer Sport Trac', 107);
insert into estacion (modelo, capacidad) values ('Roadmaster', 108);
insert into estacion (modelo, capacidad) values ('Voyager', 109);
insert into estacion (modelo, capacidad) values ('A4', 110);
insert into estacion (modelo, capacidad) values ('XC70', 111);
insert into estacion (modelo, capacidad) values ('Sportage', 112);
insert into estacion (modelo, capacidad) values ('A6', 113);
insert into estacion (modelo, capacidad) values ('Riviera', 114);
insert into estacion (modelo, capacidad) values ('MKZ', 115);
insert into estacion (modelo, capacidad) values ('Rapide', 116);
insert into estacion (modelo, capacidad) values ('V40', 117);
insert into estacion (modelo, capacidad) values ('Mazda6', 118);
insert into estacion (modelo, capacidad) values ('Riviera', 119);
insert into estacion (modelo, capacidad) values ('CX-7', 120);
insert into estacion (modelo, capacidad) values ('Z8', 121);
insert into estacion (modelo, capacidad) values ('IS', 122);
insert into estacion (modelo, capacidad) values ('Xtra', 123);
insert into estacion (modelo, capacidad) values ('LR3', 124);
insert into estacion (modelo, capacidad) values ('SJ', 125);
insert into estacion (modelo, capacidad) values ('Econoline E250', 126);
insert into estacion (modelo, capacidad) values ('Integra', 127);
insert into estacion (modelo, capacidad) values ('M3', 128);
insert into estacion (modelo, capacidad) values ('CLK-Class', 129);
insert into estacion (modelo, capacidad) values ('S2000', 130);
insert into estacion (modelo, capacidad) values ('Swift', 131);
insert into estacion (modelo, capacidad) values ('F150', 132);
insert into estacion (modelo, capacidad) values ('Aerostar', 133);
insert into estacion (modelo, capacidad) values ('S60', 134);
insert into estacion (modelo, capacidad) values ('Premier', 135);
insert into estacion (modelo, capacidad) values ('E-Series', 136);
insert into estacion (modelo, capacidad) values ('2500', 137);
insert into estacion (modelo, capacidad) values ('LS', 138);
insert into estacion (modelo, capacidad) values ('Ram 1500', 139);
insert into estacion (modelo, capacidad) values ('Karif', 140);
insert into estacion (modelo, capacidad) values ('Corvette', 141);
insert into estacion (modelo, capacidad) values ('Excursion', 142);
insert into estacion (modelo, capacidad) values ('Cavalier', 143);
insert into estacion (modelo, capacidad) values ('Grand Am', 144);
insert into estacion (modelo, capacidad) values ('Millenia', 145);
insert into estacion (modelo, capacidad) values ('Venza', 146);
insert into estacion (modelo, capacidad) values ('Corrado', 147);
insert into estacion (modelo, capacidad) values ('Concorde', 148);
insert into estacion (modelo, capacidad) values ('Alpina B7', 149);
insert into estacion (modelo, capacidad) values ('Sportage', 150);
insert into estacion (modelo, capacidad) values ('Taurus', 151);
insert into estacion (modelo, capacidad) values ('Sportvan G10', 152);
insert into estacion (modelo, capacidad) values ('Monterey', 153);
insert into estacion (modelo, capacidad) values ('Sierra 3500', 154);
insert into estacion (modelo, capacidad) values ('Azure', 155);
insert into estacion (modelo, capacidad) values ('R-Class', 156);
insert into estacion (modelo, capacidad) values ('Avenger', 157);
insert into estacion (modelo, capacidad) values ('Baja', 158);
insert into estacion (modelo, capacidad) values ('CL-Class', 159);
insert into estacion (modelo, capacidad) values ('Sunfire', 160);
insert into estacion (modelo, capacidad) values ('Fox', 161);
insert into estacion (modelo, capacidad) values ('Bronco II', 162);
insert into estacion (modelo, capacidad) values ('Century', 163);
insert into estacion (modelo, capacidad) values ('LTD Crown Victoria', 164);
insert into estacion (modelo, capacidad) values ('Savana 1500', 165);
insert into estacion (modelo, capacidad) values ('Pathfinder', 166);
insert into estacion (modelo, capacidad) values ('X3', 167);
insert into estacion (modelo, capacidad) values ('Ram Van 1500', 168);
insert into estacion (modelo, capacidad) values ('Pajero', 169);
insert into estacion (modelo, capacidad) values ('Sierra 2500', 170);
insert into estacion (modelo, capacidad) values ('Land Cruiser', 171);
insert into estacion (modelo, capacidad) values ('Grand Prix', 172);
insert into estacion (modelo, capacidad) values ('Cabriolet', 173);
insert into estacion (modelo, capacidad) values ('B-Series', 174);
insert into estacion (modelo, capacidad) values ('XJ', 175);
insert into estacion (modelo, capacidad) values ('C-Class', 176);
insert into estacion (modelo, capacidad) values ('Impreza', 177);
insert into estacion (modelo, capacidad) values ('Galant', 178);
insert into estacion (modelo, capacidad) values ('B-Series', 179);
insert into estacion (modelo, capacidad) values ('Mariner', 180);
insert into estacion (modelo, capacidad) values ('Sequoia', 181);
insert into estacion (modelo, capacidad) values ('Durango', 182);
insert into estacion (modelo, capacidad) values ('4Runner', 183);
insert into estacion (modelo, capacidad) values ('Accord', 184);
insert into estacion (modelo, capacidad) values ('Type 2', 185);
insert into estacion (modelo, capacidad) values ('DBS', 186);
insert into estacion (modelo, capacidad) values ('Roadmaster', 187);
insert into estacion (modelo, capacidad) values ('Grand Am', 188);
insert into estacion (modelo, capacidad) values ('Tundra', 189);
insert into estacion (modelo, capacidad) values ('Echo', 190);
insert into estacion (modelo, capacidad) values ('Yukon', 191);
insert into estacion (modelo, capacidad) values ('G', 192);
insert into estacion (modelo, capacidad) values ('Liberty', 193);
insert into estacion (modelo, capacidad) values ('Grand Caravan', 194);
insert into estacion (modelo, capacidad) values ('3500', 195);
insert into estacion (modelo, capacidad) values ('Mustang', 196);
insert into estacion (modelo, capacidad) values ('Sentra', 197);
insert into estacion (modelo, capacidad) values ('Familia', 198);
insert into estacion (modelo, capacidad) values ('Ram 1500', 199);
insert into estacion (modelo, capacidad) values ('Corsica', 200);
insert into estacion (modelo, capacidad) values ('Esteem', 201);
insert into estacion (modelo, capacidad) values ('Diablo', 202);
insert into estacion (modelo, capacidad) values ('Talon', 203);
insert into estacion (modelo, capacidad) values ('GranSport', 204);
insert into estacion (modelo, capacidad) values ('Express 2500', 205);
insert into estacion (modelo, capacidad) values ('Mazdaspeed6', 206);
insert into estacion (modelo, capacidad) values ('GX', 207);
insert into estacion (modelo, capacidad) values ('S8', 208);
insert into estacion (modelo, capacidad) values ('Alliance', 209);
insert into estacion (modelo, capacidad) values ('Xtra', 210);
insert into estacion (modelo, capacidad) values ('9-3', 211);
insert into estacion (modelo, capacidad) values ('A6', 212);
insert into estacion (modelo, capacidad) values ('Sephia', 213);
insert into estacion (modelo, capacidad) values ('Tracker', 214);
insert into estacion (modelo, capacidad) values ('QX', 215);
insert into estacion (modelo, capacidad) values ('Forester', 216);
insert into estacion (modelo, capacidad) values ('Diablo', 217);
insert into estacion (modelo, capacidad) values ('LeSabre', 218);
insert into estacion (modelo, capacidad) values ('9-5', 219);
insert into estacion (modelo, capacidad) values ('Vandura 2500', 220);
insert into estacion (modelo, capacidad) values ('W126', 221);
insert into estacion (modelo, capacidad) values ('Continental', 222);
insert into estacion (modelo, capacidad) values ('LR2', 223);
insert into estacion (modelo, capacidad) values ('S40', 224);
insert into estacion (modelo, capacidad) values ('CL', 225);
insert into estacion (modelo, capacidad) values ('Tempo', 226);
insert into estacion (modelo, capacidad) values ('CLS-Class', 227);
insert into estacion (modelo, capacidad) values ('5 Series', 228);
insert into estacion (modelo, capacidad) values ('Xterra', 229);
insert into estacion (modelo, capacidad) values ('Grand Marquis', 230);
insert into estacion (modelo, capacidad) values ('Topaz', 231);
insert into estacion (modelo, capacidad) values ('Prizm', 232);
insert into estacion (modelo, capacidad) values ('7 Series', 233);
insert into estacion (modelo, capacidad) values ('Dakota', 234);
insert into estacion (modelo, capacidad) values ('Express 1500', 235);
insert into estacion (modelo, capacidad) values ('Exige', 236);
insert into estacion (modelo, capacidad) values ('Trooper', 237);
insert into estacion (modelo, capacidad) values ('F-Series', 238);
insert into estacion (modelo, capacidad) values ('CX-7', 239);
insert into estacion (modelo, capacidad) values ('Liberty', 240);
insert into estacion (modelo, capacidad) values ('Suburban 1500', 241);
insert into estacion (modelo, capacidad) values ('LS', 242);
insert into estacion (modelo, capacidad) values ('Voyager', 243);
insert into estacion (modelo, capacidad) values ('D250 Club', 244);
insert into estacion (modelo, capacidad) values ('Elan', 245);
insert into estacion (modelo, capacidad) values ('Sequoia', 246);
insert into estacion (modelo, capacidad) values ('PT Cruiser', 247);
insert into estacion (modelo, capacidad) values ('CR-Z', 248);
insert into estacion (modelo, capacidad) values ('Nubira', 249);
insert into estacion (modelo, capacidad) values ('Explorer Sport Trac', 250);
insert into estacion (modelo, capacidad) values ('Mulsanne', 251);
insert into estacion (modelo, capacidad) values ('M3', 252);
insert into estacion (modelo, capacidad) values ('Spider', 253);
insert into estacion (modelo, capacidad) values ('GTI', 254);
insert into estacion (modelo, capacidad) values ('H1', 255);
insert into estacion (modelo, capacidad) values ('Aerostar', 256);
insert into estacion (modelo, capacidad) values ('Thunderbird', 257);
insert into estacion (modelo, capacidad) values ('Tahoe', 258);
insert into estacion (modelo, capacidad) values ('Silverado 3500', 259);
insert into estacion (modelo, capacidad) values ('Cultus', 260);
insert into estacion (modelo, capacidad) values ('Fox', 261);
insert into estacion (modelo, capacidad) values ('B-Series', 262);
insert into estacion (modelo, capacidad) values ('Fleetwood', 263);
insert into estacion (modelo, capacidad) values ('Solara', 264);
insert into estacion (modelo, capacidad) values ('MX-5', 265);
insert into estacion (modelo, capacidad) values ('Forester', 266);
insert into estacion (modelo, capacidad) values ('Cutlass Cruiser', 267);
insert into estacion (modelo, capacidad) values ('Silverado', 268);
insert into estacion (modelo, capacidad) values ('iQ', 269);
insert into estacion (modelo, capacidad) values ('200SX', 270);
insert into estacion (modelo, capacidad) values ('I', 271);
insert into estacion (modelo, capacidad) values ('Sonata', 272);
insert into estacion (modelo, capacidad) values ('Sierra 3500HD', 273);
insert into estacion (modelo, capacidad) values ('Expedition EL', 274);
insert into estacion (modelo, capacidad) values ('1 Series', 275);
insert into estacion (modelo, capacidad) values ('New Yorker', 276);
insert into estacion (modelo, capacidad) values ('CX-9', 277);
insert into estacion (modelo, capacidad) values ('Range Rover Evoque', 278);
insert into estacion (modelo, capacidad) values ('Caravan', 279);
insert into estacion (modelo, capacidad) values ('Yukon', 280);
insert into estacion (modelo, capacidad) values ('Navajo', 281);
insert into estacion (modelo, capacidad) values ('200', 282);
insert into estacion (modelo, capacidad) values ('Tahoe', 283);
insert into estacion (modelo, capacidad) values ('911', 284);
insert into estacion (modelo, capacidad) values ('Regal', 285);
insert into estacion (modelo, capacidad) values ('Baja', 286);
insert into estacion (modelo, capacidad) values ('A4', 287);
insert into estacion (modelo, capacidad) values ('Grand Caravan', 288);
insert into estacion (modelo, capacidad) values ('XK Series', 289);
insert into estacion (modelo, capacidad) values ('S-Class', 290);
insert into estacion (modelo, capacidad) values ('Galant', 291);
insert into estacion (modelo, capacidad) values ('LeMans', 292);
insert into estacion (modelo, capacidad) values ('Safari', 293);
insert into estacion (modelo, capacidad) values ('Suburban 1500', 294);
insert into estacion (modelo, capacidad) values ('CR-X', 295);
insert into estacion (modelo, capacidad) values ('Rogue', 296);
insert into estacion (modelo, capacidad) values ('Caravan', 297);
insert into estacion (modelo, capacidad) values ('Ram 3500', 298);
insert into estacion (modelo, capacidad) values ('Xterra', 299);
insert into estacion (modelo, capacidad) values ('88', 300);
insert into estacion (modelo, capacidad) values ('Leganza', 301);
insert into estacion (modelo, capacidad) values ('FX', 302);
insert into estacion (modelo, capacidad) values ('Boxster', 303);
insert into estacion (modelo, capacidad) values ('Neon', 304);
insert into estacion (modelo, capacidad) values ('MX-5', 305);
insert into estacion (modelo, capacidad) values ('Durango', 306);
insert into estacion (modelo, capacidad) values ('Safari', 307);
insert into estacion (modelo, capacidad) values ('DB9', 308);
insert into estacion (modelo, capacidad) values ('Galant', 309);
insert into estacion (modelo, capacidad) values ('Continental', 310);
insert into estacion (modelo, capacidad) values ('Firebird', 311);
insert into estacion (modelo, capacidad) values ('Sentra', 312);
insert into estacion (modelo, capacidad) values ('2500', 313);
insert into estacion (modelo, capacidad) values ('FX', 314);
insert into estacion (modelo, capacidad) values ('Accord', 315);
insert into estacion (modelo, capacidad) values ('CTS', 316);
insert into estacion (modelo, capacidad) values ('Ram Van 1500', 317);
insert into estacion (modelo, capacidad) values ('CR-V', 318);
insert into estacion (modelo, capacidad) values ('DB9', 319);
insert into estacion (modelo, capacidad) values ('Topaz', 320);
insert into estacion (modelo, capacidad) values ('SLK-Class', 321);
insert into estacion (modelo, capacidad) values ('Cooper', 322);
insert into estacion (modelo, capacidad) values ('Sidekick', 323);
insert into estacion (modelo, capacidad) values ('Civic', 324);
insert into estacion (modelo, capacidad) values ('XL-7', 325);
insert into estacion (modelo, capacidad) values ('S80', 326);
insert into estacion (modelo, capacidad) values ('Canyon', 327);
insert into estacion (modelo, capacidad) values ('Aerostar', 328);
insert into estacion (modelo, capacidad) values ('100', 329);
insert into estacion (modelo, capacidad) values ('Explorer', 330);
insert into estacion (modelo, capacidad) values ('Spirit', 331);
insert into estacion (modelo, capacidad) values ('Versa', 332);
insert into estacion (modelo, capacidad) values ('GTI', 333);
insert into estacion (modelo, capacidad) values ('Galant', 334);
insert into estacion (modelo, capacidad) values ('IS F', 335);
insert into estacion (modelo, capacidad) values ('Quest', 336);
insert into estacion (modelo, capacidad) values ('Altima', 337);
insert into estacion (modelo, capacidad) values ('M5', 338);
insert into estacion (modelo, capacidad) values ('Continental GTC', 339);
insert into estacion (modelo, capacidad) values ('Grand Caravan', 340);
insert into estacion (modelo, capacidad) values ('F430', 341);
insert into estacion (modelo, capacidad) values ('Montero Sport', 342);
insert into estacion (modelo, capacidad) values ('Tacoma Xtra', 343);
insert into estacion (modelo, capacidad) values ('Alcyone SVX', 344);
insert into estacion (modelo, capacidad) values ('M-Class', 345);
insert into estacion (modelo, capacidad) values ('Viper', 346);
insert into estacion (modelo, capacidad) values ('Civic', 347);
insert into estacion (modelo, capacidad) values ('Lancer', 348);
insert into estacion (modelo, capacidad) values ('Ranger', 349);
insert into estacion (modelo, capacidad) values ('Trooper', 350);
insert into estacion (modelo, capacidad) values ('240SX', 351);
insert into estacion (modelo, capacidad) values ('Reno', 352);
insert into estacion (modelo, capacidad) values ('200', 353);
insert into estacion (modelo, capacidad) values ('Pilot', 354);
insert into estacion (modelo, capacidad) values ('V70', 355);
insert into estacion (modelo, capacidad) values ('E-Series', 356);
insert into estacion (modelo, capacidad) values ('DeVille', 357);
insert into estacion (modelo, capacidad) values ('745', 358);
insert into estacion (modelo, capacidad) values ('Q', 359);
insert into estacion (modelo, capacidad) values ('Pacifica', 360);
insert into estacion (modelo, capacidad) values ('Maxima', 361);
insert into estacion (modelo, capacidad) values ('Fleetwood', 362);
insert into estacion (modelo, capacidad) values ('Monte Carlo', 363);
insert into estacion (modelo, capacidad) values ('Sentra', 364);
insert into estacion (modelo, capacidad) values ('Escalade ESV', 365);
insert into estacion (modelo, capacidad) values ('DeVille', 366);
insert into estacion (modelo, capacidad) values ('TundraMax', 367);
insert into estacion (modelo, capacidad) values ('rio', 368);
insert into estacion (modelo, capacidad) values ('Navigator', 369);
insert into estacion (modelo, capacidad) values ('Estate', 370);
insert into estacion (modelo, capacidad) values ('TT', 371);
insert into estacion (modelo, capacidad) values ('Q', 372);
insert into estacion (modelo, capacidad) values ('Safari', 373);
insert into estacion (modelo, capacidad) values ('Murciélago', 374);
insert into estacion (modelo, capacidad) values ('F350', 375);
insert into estacion (modelo, capacidad) values ('S10', 376);
insert into estacion (modelo, capacidad) values ('Express 2500', 377);
insert into estacion (modelo, capacidad) values ('GLK-Class', 378);
insert into estacion (modelo, capacidad) values ('Express 2500', 379);
insert into estacion (modelo, capacidad) values ('Laser', 380);
insert into estacion (modelo, capacidad) values ('Camaro', 381);
insert into estacion (modelo, capacidad) values ('Monte Carlo', 382);
insert into estacion (modelo, capacidad) values ('Firefly', 383);
insert into estacion (modelo, capacidad) values ('B-Series Plus', 384);
insert into estacion (modelo, capacidad) values ('SC', 385);
insert into estacion (modelo, capacidad) values ('R32', 386);
insert into estacion (modelo, capacidad) values ('6 Series', 387);
insert into estacion (modelo, capacidad) values ('Miata MX-5', 388);
insert into estacion (modelo, capacidad) values ('SC', 389);
insert into estacion (modelo, capacidad) values ('riolet', 390);
insert into estacion (modelo, capacidad) values ('Range Rover', 391);
insert into estacion (modelo, capacidad) values ('Sephia', 392);
insert into estacion (modelo, capacidad) values ('Sienna', 393);
insert into estacion (modelo, capacidad) values ('EXP', 394);
insert into estacion (modelo, capacidad) values ('Sonata', 395);
insert into estacion (modelo, capacidad) values ('Ram 3500', 396);
insert into estacion (modelo, capacidad) values ('Camry Solara', 397);
insert into estacion (modelo, capacidad) values ('Civic', 398);
insert into estacion (modelo, capacidad) values ('Magnum', 399);
insert into estacion (modelo, capacidad) values ('Minx Magnificent', 400);
insert into estacion (modelo, capacidad) values ('New Yorker', 401);
insert into estacion (modelo, capacidad) values ('Outback', 402);
insert into estacion (modelo, capacidad) values ('IS-F', 403);
insert into estacion (modelo, capacidad) values ('600', 404);
insert into estacion (modelo, capacidad) values ('Chariot', 405);
insert into estacion (modelo, capacidad) values ('Fortwo', 406);
insert into estacion (modelo, capacidad) values ('Eclipse', 407);
insert into estacion (modelo, capacidad) values ('CR-V', 408);
insert into estacion (modelo, capacidad) values ('F-Series', 409);
insert into estacion (modelo, capacidad) values ('RX-7', 410);
insert into estacion (modelo, capacidad) values ('E350', 411);
insert into estacion (modelo, capacidad) values ('Mustang', 412);
insert into estacion (modelo, capacidad) values ('Sentra', 413);
insert into estacion (modelo, capacidad) values ('Familia', 414);
insert into estacion (modelo, capacidad) values ('B-Series Plus', 415);
insert into estacion (modelo, capacidad) values ('Yukon', 416);
insert into estacion (modelo, capacidad) values ('Outback', 417);
insert into estacion (modelo, capacidad) values ('Thunderbird', 418);
insert into estacion (modelo, capacidad) values ('Tribute', 419);
insert into estacion (modelo, capacidad) values ('Jetta', 420);
insert into estacion (modelo, capacidad) values ('Viper', 421);
insert into estacion (modelo, capacidad) values ('SL-Class', 422);
insert into estacion (modelo, capacidad) values ('Sportvan G10', 423);
insert into estacion (modelo, capacidad) values ('NV3500', 424);
insert into estacion (modelo, capacidad) values ('57', 425);
insert into estacion (modelo, capacidad) values ('Exige', 426);
insert into estacion (modelo, capacidad) values ('LSS', 427);
insert into estacion (modelo, capacidad) values ('Diamante', 428);
insert into estacion (modelo, capacidad) values ('GX', 429);
insert into estacion (modelo, capacidad) values ('Park Avenue', 430);
insert into estacion (modelo, capacidad) values ('Sentra', 431);
insert into estacion (modelo, capacidad) values ('Elantra', 432);
insert into estacion (modelo, capacidad) values ('Civic', 433);
insert into estacion (modelo, capacidad) values ('Pilot', 434);
insert into estacion (modelo, capacidad) values ('Ram Van 3500', 435);
insert into estacion (modelo, capacidad) values ('Solara', 436);
insert into estacion (modelo, capacidad) values ('Jetta', 437);
insert into estacion (modelo, capacidad) values ('Envoy XL', 438);
insert into estacion (modelo, capacidad) values ('SLR McLaren', 439);
insert into estacion (modelo, capacidad) values ('Oasis', 440);
insert into estacion (modelo, capacidad) values ('Caravan', 441);
insert into estacion (modelo, capacidad) values ('Santa Fe', 442);
insert into estacion (modelo, capacidad) values ('Ipsum', 443);
insert into estacion (modelo, capacidad) values ('Sedona', 444);
insert into estacion (modelo, capacidad) values ('Escalade EXT', 445);
insert into estacion (modelo, capacidad) values ('Malibu', 446);
insert into estacion (modelo, capacidad) values ('Grand Am', 447);
insert into estacion (modelo, capacidad) values ('F250', 448);
insert into estacion (modelo, capacidad) values ('Firebird', 449);
insert into estacion (modelo, capacidad) values ('Windstar', 450);
insert into estacion (modelo, capacidad) values ('SVX', 451);
insert into estacion (modelo, capacidad) values ('Suburban 2500', 452);
insert into estacion (modelo, capacidad) values ('S-Class', 453);
insert into estacion (modelo, capacidad) values ('2500', 454);
insert into estacion (modelo, capacidad) values ('Shadow', 455);
insert into estacion (modelo, capacidad) values ('Monte Carlo', 456);
insert into estacion (modelo, capacidad) values ('GTI', 457);
insert into estacion (modelo, capacidad) values ('Caravan', 458);
insert into estacion (modelo, capacidad) values ('Cougar', 459);
insert into estacion (modelo, capacidad) values ('Stealth', 460);
insert into estacion (modelo, capacidad) values ('Vandura 1500', 461);
insert into estacion (modelo, capacidad) values ('Vandura G1500', 462);
insert into estacion (modelo, capacidad) values ('Suburban 1500', 463);
insert into estacion (modelo, capacidad) values ('Mustang', 464);
insert into estacion (modelo, capacidad) values ('Century', 465);
insert into estacion (modelo, capacidad) values ('Ram Wagon B150', 466);
insert into estacion (modelo, capacidad) values ('ZDX', 467);
insert into estacion (modelo, capacidad) values ('QX', 468);
insert into estacion (modelo, capacidad) values ('Protege', 469);
insert into estacion (modelo, capacidad) values ('Optima', 470);
insert into estacion (modelo, capacidad) values ('S60', 471);
insert into estacion (modelo, capacidad) values ('Bonneville', 472);
insert into estacion (modelo, capacidad) values ('Ram 1500', 473);
insert into estacion (modelo, capacidad) values ('Savana 2500', 474);
insert into estacion (modelo, capacidad) values ('Ascender', 475);
insert into estacion (modelo, capacidad) values ('Armada', 476);
insert into estacion (modelo, capacidad) values ('Dakota Club', 477);
insert into estacion (modelo, capacidad) values ('9000', 478);
insert into estacion (modelo, capacidad) values ('Blazer', 479);
insert into estacion (modelo, capacidad) values ('Exige', 480);
insert into estacion (modelo, capacidad) values ('Grand Prix', 481);
insert into estacion (modelo, capacidad) values ('Montero', 482);
insert into estacion (modelo, capacidad) values ('Riviera', 483);
insert into estacion (modelo, capacidad) values ('Town Car', 484);
insert into estacion (modelo, capacidad) values ('MR2', 485);
insert into estacion (modelo, capacidad) values ('Grand Prix', 486);
insert into estacion (modelo, capacidad) values ('TL', 487);
insert into estacion (modelo, capacidad) values ('STS', 488);
insert into estacion (modelo, capacidad) values ('Eurovan', 489);
insert into estacion (modelo, capacidad) values ('SLK-Class', 490);
insert into estacion (modelo, capacidad) values ('TL', 491);
insert into estacion (modelo, capacidad) values ('X5 M', 492);
insert into estacion (modelo, capacidad) values ('New Beetle', 493);
insert into estacion (modelo, capacidad) values ('X6', 494);
insert into estacion (modelo, capacidad) values ('Econoline E150', 495);
insert into estacion (modelo, capacidad) values ('Cougar', 496);
insert into estacion (modelo, capacidad) values ('Avalanche 2500', 497);
insert into estacion (modelo, capacidad) values ('3 Series', 498);
insert into estacion (modelo, capacidad) values ('80', 499);
insert into estacion (modelo, capacidad) values ('Crown Victoria', 500);
insert into estacion (modelo, capacidad) values ('Santa Fe', 501);
insert into estacion (modelo, capacidad) values ('9-2X', 502);
insert into estacion (modelo, capacidad) values ('Golf III', 503);
insert into estacion (modelo, capacidad) values ('SL-Class', 504);
insert into estacion (modelo, capacidad) values ('Blazer', 505);
insert into estacion (modelo, capacidad) values ('Five Hundred', 506);
insert into estacion (modelo, capacidad) values ('SSR', 507);
insert into estacion (modelo, capacidad) values ('G-Class', 508);
insert into estacion (modelo, capacidad) values ('Corvair', 509);
insert into estacion (modelo, capacidad) values ('Viper RT/10', 510);
insert into estacion (modelo, capacidad) values ('S2000', 511);
insert into estacion (modelo, capacidad) values ('Cherokee', 512);
insert into estacion (modelo, capacidad) values ('Continental GT', 513);
insert into estacion (modelo, capacidad) values ('Ram 2500 Club', 514);
insert into estacion (modelo, capacidad) values ('Veloster', 515);
insert into estacion (modelo, capacidad) values ('Tiburon', 516);
insert into estacion (modelo, capacidad) values ('Cougar', 517);
insert into estacion (modelo, capacidad) values ('S80', 518);
insert into estacion (modelo, capacidad) values ('Voyager', 519);
insert into estacion (modelo, capacidad) values ('Taurus', 520);
insert into estacion (modelo, capacidad) values ('9000', 521);
insert into estacion (modelo, capacidad) values ('Ram Van B250', 522);
insert into estacion (modelo, capacidad) values ('GTI', 523);
insert into estacion (modelo, capacidad) values ('Crown Victoria', 524);
insert into estacion (modelo, capacidad) values ('Montero Sport', 525);
insert into estacion (modelo, capacidad) values ('J', 526);
insert into estacion (modelo, capacidad) values ('Vision', 527);
insert into estacion (modelo, capacidad) values ('Transit Connect', 528);
insert into estacion (modelo, capacidad) values ('GT-R', 529);
insert into estacion (modelo, capacidad) values ('Silverado 2500', 530);
insert into estacion (modelo, capacidad) values ('F350', 531);
insert into estacion (modelo, capacidad) values ('Wrangler', 532);
insert into estacion (modelo, capacidad) values ('Summit', 533);
insert into estacion (modelo, capacidad) values ('3500', 534);
insert into estacion (modelo, capacidad) values ('Tahoe', 535);
insert into estacion (modelo, capacidad) values ('RS 6', 536);
insert into estacion (modelo, capacidad) values ('MX-3', 537);
insert into estacion (modelo, capacidad) values ('CR-V', 538);
insert into estacion (modelo, capacidad) values ('Escalade', 539);
insert into estacion (modelo, capacidad) values ('Mark VIII', 540);
insert into estacion (modelo, capacidad) values ('Q', 541);
insert into estacion (modelo, capacidad) values ('Avanti', 542);
insert into estacion (modelo, capacidad) values ('W201', 543);
insert into estacion (modelo, capacidad) values ('Caliber', 544);
insert into estacion (modelo, capacidad) values ('ES', 545);
insert into estacion (modelo, capacidad) values ('Cabriolet', 546);
insert into estacion (modelo, capacidad) values ('Silverado 3500', 547);
insert into estacion (modelo, capacidad) values ('Ranger', 548);
insert into estacion (modelo, capacidad) values ('Cordia', 549);
insert into estacion (modelo, capacidad) values ('F350', 550);
insert into estacion (modelo, capacidad) values ('Corvette', 551);
insert into estacion (modelo, capacidad) values ('LS', 552);
insert into estacion (modelo, capacidad) values ('E-Class', 553);
insert into estacion (modelo, capacidad) values ('Firebird', 554);
insert into estacion (modelo, capacidad) values ('Sonoma', 555);
insert into estacion (modelo, capacidad) values ('Navajo', 556);
insert into estacion (modelo, capacidad) values ('Regal', 557);
insert into estacion (modelo, capacidad) values ('STS', 558);
insert into estacion (modelo, capacidad) values ('Ranger', 559);
insert into estacion (modelo, capacidad) values ('Boxster', 560);
insert into estacion (modelo, capacidad) values ('Ram 1500 Club', 561);
insert into estacion (modelo, capacidad) values ('Durango', 562);
insert into estacion (modelo, capacidad) values ('S2000', 563);
insert into estacion (modelo, capacidad) values ('626', 564);
insert into estacion (modelo, capacidad) values ('Accent', 565);
insert into estacion (modelo, capacidad) values ('IS-F', 566);
insert into estacion (modelo, capacidad) values ('Mohave/Borrego', 567);
insert into estacion (modelo, capacidad) values ('Somerset', 568);
insert into estacion (modelo, capacidad) values ('Sorento', 569);
insert into estacion (modelo, capacidad) values ('Tacoma', 570);
insert into estacion (modelo, capacidad) values ('Metro', 571);
insert into estacion (modelo, capacidad) values ('Challenger', 572);
insert into estacion (modelo, capacidad) values ('QX', 573);
insert into estacion (modelo, capacidad) values ('SX4', 574);
insert into estacion (modelo, capacidad) values ('Capri', 575);
insert into estacion (modelo, capacidad) values ('Caprice', 576);
insert into estacion (modelo, capacidad) values ('9-3', 577);
insert into estacion (modelo, capacidad) values ('Frontier', 578);
insert into estacion (modelo, capacidad) values ('M3', 579);
insert into estacion (modelo, capacidad) values ('Firefly', 580);
insert into estacion (modelo, capacidad) values ('Rio5', 581);
insert into estacion (modelo, capacidad) values ('Bonneville', 582);
insert into estacion (modelo, capacidad) values ('Tiburon', 583);
insert into estacion (modelo, capacidad) values ('Viper', 584);
insert into estacion (modelo, capacidad) values ('Charger', 585);
insert into estacion (modelo, capacidad) values ('G6', 586);
insert into estacion (modelo, capacidad) values ('929', 587);
insert into estacion (modelo, capacidad) values ('Corvette', 588);
insert into estacion (modelo, capacidad) values ('RSX', 589);
insert into estacion (modelo, capacidad) values ('Firebird', 590);
insert into estacion (modelo, capacidad) values ('Sienna', 591);
insert into estacion (modelo, capacidad) values ('Silverado', 592);
insert into estacion (modelo, capacidad) values ('Grand Marquis', 593);
insert into estacion (modelo, capacidad) values ('Eclipse', 594);
insert into estacion (modelo, capacidad) values ('CR-V', 595);
insert into estacion (modelo, capacidad) values ('S-Type', 596);
insert into estacion (modelo, capacidad) values ('S10', 597);
insert into estacion (modelo, capacidad) values ('Grand Vitara', 598);
insert into estacion (modelo, capacidad) values ('Sienna', 599);
insert into estacion (modelo, capacidad) values ('Spectra', 600);
insert into estacion (modelo, capacidad) values ('IS-F', 601);
insert into estacion (modelo, capacidad) values ('C70', 602);
insert into estacion (modelo, capacidad) values ('Flex', 603);
insert into estacion (modelo, capacidad) values ('Rondo', 604);
insert into estacion (modelo, capacidad) values ('C70', 605);
insert into estacion (modelo, capacidad) values ('Grand Caravan', 606);
insert into estacion (modelo, capacidad) values ('Sonoma', 607);
insert into estacion (modelo, capacidad) values ('Savana', 608);
insert into estacion (modelo, capacidad) values ('Sportage', 609);
insert into estacion (modelo, capacidad) values ('Caprice Classic', 610);
insert into estacion (modelo, capacidad) values ('SLK-Class', 611);
insert into estacion (modelo, capacidad) values ('Ion', 612);
insert into estacion (modelo, capacidad) values ('SJ', 613);
insert into estacion (modelo, capacidad) values ('Skylark', 614);
insert into estacion (modelo, capacidad) values ('STS-V', 615);
insert into estacion (modelo, capacidad) values ('RVR', 616);
insert into estacion (modelo, capacidad) values ('Yaris', 617);
insert into estacion (modelo, capacidad) values ('Odyssey', 618);
insert into estacion (modelo, capacidad) values ('500E', 619);
insert into estacion (modelo, capacidad) values ('Suburban 1500', 620);
insert into estacion (modelo, capacidad) values ('DTS', 621);
insert into estacion (modelo, capacidad) values ('Talon', 622);
insert into estacion (modelo, capacidad) values ('3000GT', 623);
insert into estacion (modelo, capacidad) values ('TT', 624);
insert into estacion (modelo, capacidad) values ('Prelude', 625);
insert into estacion (modelo, capacidad) values ('Quattroporte', 626);
insert into estacion (modelo, capacidad) values ('Leaf', 627);
insert into estacion (modelo, capacidad) values ('Neon', 628);
insert into estacion (modelo, capacidad) values ('Taurus', 629);
insert into estacion (modelo, capacidad) values ('Tundra', 630);
insert into estacion (modelo, capacidad) values ('Camaro', 631);
insert into estacion (modelo, capacidad) values ('Falcon', 632);
insert into estacion (modelo, capacidad) values ('Savana', 633);
insert into estacion (modelo, capacidad) values ('90', 634);
insert into estacion (modelo, capacidad) values ('9-3', 635);
insert into estacion (modelo, capacidad) values ('Corolla', 636);
insert into estacion (modelo, capacidad) values ('Sigma', 637);
insert into estacion (modelo, capacidad) values ('Stealth', 638);
insert into estacion (modelo, capacidad) values ('Camry', 639);
insert into estacion (modelo, capacidad) values ('L-Series', 640);
insert into estacion (modelo, capacidad) values ('Avanti', 641);
insert into estacion (modelo, capacidad) values ('Jetta', 642);
insert into estacion (modelo, capacidad) values ('Rally Wagon 1500', 643);
insert into estacion (modelo, capacidad) values ('GTI', 644);
insert into estacion (modelo, capacidad) values ('CTS-V', 645);
insert into estacion (modelo, capacidad) values ('Diablo', 646);
insert into estacion (modelo, capacidad) values ('Bonneville', 647);
insert into estacion (modelo, capacidad) values ('MX-5', 648);
insert into estacion (modelo, capacidad) values ('CTS-V', 649);
insert into estacion (modelo, capacidad) values ('Tiguan', 650);
insert into estacion (modelo, capacidad) values ('3500', 651);
insert into estacion (modelo, capacidad) values ('B-Series', 652);
insert into estacion (modelo, capacidad) values ('Truck', 653);
insert into estacion (modelo, capacidad) values ('4Runner', 654);
insert into estacion (modelo, capacidad) values ('Yukon', 655);
insert into estacion (modelo, capacidad) values ('Verona', 656);
insert into estacion (modelo, capacidad) values ('GTI', 657);
insert into estacion (modelo, capacidad) values ('F250', 658);
insert into estacion (modelo, capacidad) values ('Endeavor', 659);
insert into estacion (modelo, capacidad) values ('Cabriolet', 660);
insert into estacion (modelo, capacidad) values ('Eclipse', 661);
insert into estacion (modelo, capacidad) values ('3500', 662);
insert into estacion (modelo, capacidad) values ('Yukon', 663);
insert into estacion (modelo, capacidad) values ('Corvette', 664);
insert into estacion (modelo, capacidad) values ('Mirage', 665);
insert into estacion (modelo, capacidad) values ('MR2', 666);
insert into estacion (modelo, capacidad) values ('Cutlass Supreme', 667);
insert into estacion (modelo, capacidad) values ('Rendezvous', 668);
insert into estacion (modelo, capacidad) values ('Z4', 669);
insert into estacion (modelo, capacidad) values ('Suburban 2500', 670);
insert into estacion (modelo, capacidad) values ('5 Series', 671);
insert into estacion (modelo, capacidad) values ('Fiero', 672);
insert into estacion (modelo, capacidad) values ('5000S', 673);
insert into estacion (modelo, capacidad) values ('Mirage', 674);
insert into estacion (modelo, capacidad) values ('Continental GTC', 675);
insert into estacion (modelo, capacidad) values ('Tribute', 676);
insert into estacion (modelo, capacidad) values ('RAV4', 677);
insert into estacion (modelo, capacidad) values ('Shadow', 678);
insert into estacion (modelo, capacidad) values ('MKT', 679);
insert into estacion (modelo, capacidad) values ('Lumina', 680);
insert into estacion (modelo, capacidad) values ('Somerset', 681);
insert into estacion (modelo, capacidad) values ('B-Series Plus', 682);
insert into estacion (modelo, capacidad) values ('G-Class', 683);
insert into estacion (modelo, capacidad) values ('CX-7', 684);
insert into estacion (modelo, capacidad) values ('928', 685);
insert into estacion (modelo, capacidad) values ('928', 686);
insert into estacion (modelo, capacidad) values ('7 Series', 687);
insert into estacion (modelo, capacidad) values ('Bonneville', 688);
insert into estacion (modelo, capacidad) values ('7 Series', 689);
insert into estacion (modelo, capacidad) values ('Malibu', 690);
insert into estacion (modelo, capacidad) values ('RL', 691);
insert into estacion (modelo, capacidad) values ('Stealth', 692);
insert into estacion (modelo, capacidad) values ('Wrangler', 693);
insert into estacion (modelo, capacidad) values ('Tahoe', 694);
insert into estacion (modelo, capacidad) values ('Ram Van 2500', 695);
insert into estacion (modelo, capacidad) values ('Montana', 696);
insert into estacion (modelo, capacidad) values ('X6 M', 697);
insert into estacion (modelo, capacidad) values ('Dakota', 698);
insert into estacion (modelo, capacidad) values ('GTO', 699);
insert into estacion (modelo, capacidad) values ('Savana', 700);
insert into estacion (modelo, capacidad) values ('Freelander', 701);
insert into estacion (modelo, capacidad) values ('SLR McLaren', 702);
insert into estacion (modelo, capacidad) values ('Samurai', 703);
insert into estacion (modelo, capacidad) values ('1500 Club Coupe', 704);
insert into estacion (modelo, capacidad) values ('Grand Prix', 705);
insert into estacion (modelo, capacidad) values ('V70', 706);
insert into estacion (modelo, capacidad) values ('M-Class', 707);
insert into estacion (modelo, capacidad) values ('Express 2500', 708);
insert into estacion (modelo, capacidad) values ('Savana 2500', 709);
insert into estacion (modelo, capacidad) values ('Pilot', 710);
insert into estacion (modelo, capacidad) values ('Discovery', 711);
insert into estacion (modelo, capacidad) values ('Town Car', 712);
insert into estacion (modelo, capacidad) values ('626', 713);
insert into estacion (modelo, capacidad) values ('LS', 714);
insert into estacion (modelo, capacidad) values ('Bravada', 715);
insert into estacion (modelo, capacidad) values ('Optima', 716);
insert into estacion (modelo, capacidad) values ('Outback', 717);
insert into estacion (modelo, capacidad) values ('Fortwo', 718);
insert into estacion (modelo, capacidad) values ('V70', 719);
insert into estacion (modelo, capacidad) values ('Maxima', 720);
insert into estacion (modelo, capacidad) values ('Liberty', 721);
insert into estacion (modelo, capacidad) values ('F250', 722);
insert into estacion (modelo, capacidad) values ('Fox', 723);
insert into estacion (modelo, capacidad) values ('Passport', 724);
insert into estacion (modelo, capacidad) values ('Tundra', 725);
insert into estacion (modelo, capacidad) values ('Cayenne', 726);
insert into estacion (modelo, capacidad) values ('M', 727);
insert into estacion (modelo, capacidad) values ('RS6', 728);
insert into estacion (modelo, capacidad) values ('Panamera', 729);
insert into estacion (modelo, capacidad) values ('Legend', 730);
insert into estacion (modelo, capacidad) values ('Tundra', 731);
insert into estacion (modelo, capacidad) values ('XJ', 732);
insert into estacion (modelo, capacidad) values ('Sterling', 733);
insert into estacion (modelo, capacidad) values ('SRX', 734);
insert into estacion (modelo, capacidad) values ('Econoline E350', 735);
insert into estacion (modelo, capacidad) values ('Neon', 736);
insert into estacion (modelo, capacidad) values ('Econoline E250', 737);
insert into estacion (modelo, capacidad) values ('Veracruz', 738);
insert into estacion (modelo, capacidad) values ('98', 739);
insert into estacion (modelo, capacidad) values ('Ram 1500 Club', 740);
insert into estacion (modelo, capacidad) values ('Thunderbird', 741);
insert into estacion (modelo, capacidad) values ('E-Class', 742);
insert into estacion (modelo, capacidad) values ('SLR McLaren', 743);
insert into estacion (modelo, capacidad) values ('S-Series', 744);
insert into estacion (modelo, capacidad) values ('9-4X', 745);
insert into estacion (modelo, capacidad) values ('Tempest', 746);
insert into estacion (modelo, capacidad) values ('Diablo', 747);
insert into estacion (modelo, capacidad) values ('H1', 748);
insert into estacion (modelo, capacidad) values ('Dakota Club', 749);
insert into estacion (modelo, capacidad) values ('Elantra', 750);
insert into estacion (modelo, capacidad) values ('S5', 751);
insert into estacion (modelo, capacidad) values ('Biturbo', 752);
insert into estacion (modelo, capacidad) values ('Aerostar', 753);
insert into estacion (modelo, capacidad) values ('9000', 754);
insert into estacion (modelo, capacidad) values ('MR2', 755);
insert into estacion (modelo, capacidad) values ('F-Series', 756);
insert into estacion (modelo, capacidad) values ('Civic', 757);
insert into estacion (modelo, capacidad) values ('Impulse', 758);
insert into estacion (modelo, capacidad) values ('Tredia', 759);
insert into estacion (modelo, capacidad) values ('Biturbo', 760);
insert into estacion (modelo, capacidad) values ('Truck', 761);
insert into estacion (modelo, capacidad) values ('QX', 762);
insert into estacion (modelo, capacidad) values ('Bonneville', 763);
insert into estacion (modelo, capacidad) values ('S8', 764);
insert into estacion (modelo, capacidad) values ('Blazer', 765);
insert into estacion (modelo, capacidad) values ('Sentra', 766);
insert into estacion (modelo, capacidad) values ('Miata MX-5', 767);
insert into estacion (modelo, capacidad) values ('QX', 768);
insert into estacion (modelo, capacidad) values ('Bonneville', 769);
insert into estacion (modelo, capacidad) values ('Sierra 2500HD', 770);
insert into estacion (modelo, capacidad) values ('Sportage', 771);
insert into estacion (modelo, capacidad) values ('Caliber', 772);
insert into estacion (modelo, capacidad) values ('Sorento', 773);
insert into estacion (modelo, capacidad) values ('M3', 774);
insert into estacion (modelo, capacidad) values ('E-Series', 775);
insert into estacion (modelo, capacidad) values ('Land Cruiser', 776);
insert into estacion (modelo, capacidad) values ('Grand Marquis', 777);
insert into estacion (modelo, capacidad) values ('XLR', 778);
insert into estacion (modelo, capacidad) values ('Precis', 779);
insert into estacion (modelo, capacidad) values ('Elantra', 780);
insert into estacion (modelo, capacidad) values ('Rally Wagon G2500', 781);
insert into estacion (modelo, capacidad) values ('3 Series', 782);
insert into estacion (modelo, capacidad) values ('Pathfinder', 783);
insert into estacion (modelo, capacidad) values ('F-Series', 784);
insert into estacion (modelo, capacidad) values ('Sportvan G30', 785);
insert into estacion (modelo, capacidad) values ('Corvette', 786);
insert into estacion (modelo, capacidad) values ('M', 787);
insert into estacion (modelo, capacidad) values ('XC60', 788);
insert into estacion (modelo, capacidad) values ('Shadow', 789);
insert into estacion (modelo, capacidad) values ('F-Series', 790);
insert into estacion (modelo, capacidad) values ('Taurus', 791);
insert into estacion (modelo, capacidad) values ('600SEL', 792);
insert into estacion (modelo, capacidad) values ('Galaxie', 793);
insert into estacion (modelo, capacidad) values ('Tracker', 794);
insert into estacion (modelo, capacidad) values ('Mazdaspeed 3', 795);
insert into estacion (modelo, capacidad) values ('S4', 796);
insert into estacion (modelo, capacidad) values ('Esprit', 797);
insert into estacion (modelo, capacidad) values ('E-Class', 798);
insert into estacion (modelo, capacidad) values ('Ram 3500', 799);
insert into estacion (modelo, capacidad) values ('Boxster', 800);
insert into estacion (modelo, capacidad) values ('Savana 1500', 801);
insert into estacion (modelo, capacidad) values ('F150', 802);
insert into estacion (modelo, capacidad) values ('Civic', 803);
insert into estacion (modelo, capacidad) values ('L300', 804);
insert into estacion (modelo, capacidad) values ('200SX', 805);
insert into estacion (modelo, capacidad) values ('Pajero', 806);
insert into estacion (modelo, capacidad) values ('Mustang', 807);
insert into estacion (modelo, capacidad) values ('Parisienne', 808);
insert into estacion (modelo, capacidad) values ('NSX', 809);
insert into estacion (modelo, capacidad) values ('LS', 810);
insert into estacion (modelo, capacidad) values ('A8', 811);
insert into estacion (modelo, capacidad) values ('XC90', 812);
insert into estacion (modelo, capacidad) values ('M3', 813);
insert into estacion (modelo, capacidad) values ('E-350 Super Duty', 814);
insert into estacion (modelo, capacidad) values ('3000GT', 815);
insert into estacion (modelo, capacidad) values ('Continental Flying Spur', 816);
insert into estacion (modelo, capacidad) values ('Civic', 817);
insert into estacion (modelo, capacidad) values ('Sportage', 818);
insert into estacion (modelo, capacidad) values ('Celica', 819);
insert into estacion (modelo, capacidad) values ('Boxster', 820);
insert into estacion (modelo, capacidad) values ('ES', 821);
insert into estacion (modelo, capacidad) values ('Quest', 822);
insert into estacion (modelo, capacidad) values ('S-Class', 823);
insert into estacion (modelo, capacidad) values ('S80', 824);
insert into estacion (modelo, capacidad) values ('Silhouette', 825);
insert into estacion (modelo, capacidad) values ('Sequoia', 826);
insert into estacion (modelo, capacidad) values ('Avenger', 827);
insert into estacion (modelo, capacidad) values ('Cougar', 828);
insert into estacion (modelo, capacidad) values ('Ion', 829);
insert into estacion (modelo, capacidad) values ('GX', 830);
insert into estacion (modelo, capacidad) values ('Pathfinder', 831);
insert into estacion (modelo, capacidad) values ('Escalade', 832);
insert into estacion (modelo, capacidad) values ('S4', 833);
insert into estacion (modelo, capacidad) values ('Sierra 3500', 834);
insert into estacion (modelo, capacidad) values ('STS', 835);
insert into estacion (modelo, capacidad) values ('Taurus', 836);
insert into estacion (modelo, capacidad) values ('H2', 837);
insert into estacion (modelo, capacidad) values ('Town Car', 838);
insert into estacion (modelo, capacidad) values ('9-7X', 839);
insert into estacion (modelo, capacidad) values ('2500', 840);
insert into estacion (modelo, capacidad) values ('XJ Series', 841);
insert into estacion (modelo, capacidad) values ('928', 842);
insert into estacion (modelo, capacidad) values ('Yukon XL 2500', 843);
insert into estacion (modelo, capacidad) values ('GS', 844);
insert into estacion (modelo, capacidad) values ('Pajero', 845);
insert into estacion (modelo, capacidad) values ('Corvette', 846);
insert into estacion (modelo, capacidad) values ('Jetta', 847);
insert into estacion (modelo, capacidad) values ('Discovery Series II', 848);
insert into estacion (modelo, capacidad) values ('1500', 849);
insert into estacion (modelo, capacidad) values ('911', 850);
insert into estacion (modelo, capacidad) values ('Mazda2', 851);
insert into estacion (modelo, capacidad) values ('Escape', 852);
insert into estacion (modelo, capacidad) values ('Miata MX-5', 853);
insert into estacion (modelo, capacidad) values ('4000s', 854);
insert into estacion (modelo, capacidad) values ('GranTurismo', 855);
insert into estacion (modelo, capacidad) values ('Ram Van 2500', 856);
insert into estacion (modelo, capacidad) values ('Exige', 857);
insert into estacion (modelo, capacidad) values ('Ram Van 3500', 858);
insert into estacion (modelo, capacidad) values ('Express 1500', 859);
insert into estacion (modelo, capacidad) values ('530', 860);
insert into estacion (modelo, capacidad) values ('Park Avenue', 861);
insert into estacion (modelo, capacidad) values ('Continental', 862);
insert into estacion (modelo, capacidad) values ('Montero', 863);
insert into estacion (modelo, capacidad) values ('E150', 864);
insert into estacion (modelo, capacidad) values ('Safari', 865);
insert into estacion (modelo, capacidad) values ('Mirage', 866);
insert into estacion (modelo, capacidad) values ('Cayenne', 867);
insert into estacion (modelo, capacidad) values ('GLI', 868);
insert into estacion (modelo, capacidad) values ('H3', 869);
insert into estacion (modelo, capacidad) values ('GTI', 870);
insert into estacion (modelo, capacidad) values ('57', 871);
insert into estacion (modelo, capacidad) values ('Bronco', 872);
insert into estacion (modelo, capacidad) values ('Grand Cherokee', 873);
insert into estacion (modelo, capacidad) values ('Rio5', 874);
insert into estacion (modelo, capacidad) values ('Tacoma', 875);
insert into estacion (modelo, capacidad) values ('911', 876);
insert into estacion (modelo, capacidad) values ('Montero', 877);
insert into estacion (modelo, capacidad) values ('Optima', 878);
insert into estacion (modelo, capacidad) values ('Aurora', 879);
insert into estacion (modelo, capacidad) values ('Sierra 3500HD', 880);
insert into estacion (modelo, capacidad) values ('Fifth Ave', 881);
insert into estacion (modelo, capacidad) values ('del Sol', 882);
insert into estacion (modelo, capacidad) values ('Millenia', 883);
insert into estacion (modelo, capacidad) values ('Milan', 884);
insert into estacion (modelo, capacidad) values ('Voyager', 885);
insert into estacion (modelo, capacidad) values ('Vantage', 886);
insert into estacion (modelo, capacidad) values ('F250', 887);
insert into estacion (modelo, capacidad) values ('Grand Prix', 888);
insert into estacion (modelo, capacidad) values ('XK Series', 889);
insert into estacion (modelo, capacidad) values ('DeVille', 890);
insert into estacion (modelo, capacidad) values ('2500 Club Coupe', 891);
insert into estacion (modelo, capacidad) values ('Diamante', 892);
insert into estacion (modelo, capacidad) values ('Yaris', 893);
insert into estacion (modelo, capacidad) values ('SRX', 894);
insert into estacion (modelo, capacidad) values ('Lumina APV', 895);
insert into estacion (modelo, capacidad) values ('Outlander Sport', 896);
insert into estacion (modelo, capacidad) values ('9-5', 897);
insert into estacion (modelo, capacidad) values ('Panamera', 898);
insert into estacion (modelo, capacidad) values ('SL-Class', 899);
insert into estacion (modelo, capacidad) values ('Cayenne', 900);
insert into estacion (modelo, capacidad) values ('Grand Caravan', 901);
insert into estacion (modelo, capacidad) values ('Elantra', 902);
insert into estacion (modelo, capacidad) values ('9-2X', 903);
insert into estacion (modelo, capacidad) values ('GTO', 904);
insert into estacion (modelo, capacidad) values ('Econoline E150', 905);
insert into estacion (modelo, capacidad) values ('Volare', 906);
insert into estacion (modelo, capacidad) values ('9-2X', 907);
insert into estacion (modelo, capacidad) values ('Allroad', 908);
insert into estacion (modelo, capacidad) values ('Caravan', 909);
insert into estacion (modelo, capacidad) values ('300E', 910);
insert into estacion (modelo, capacidad) values ('GranSport', 911);
insert into estacion (modelo, capacidad) values ('Tacoma', 912);
insert into estacion (modelo, capacidad) values ('Storm', 913);
insert into estacion (modelo, capacidad) values ('G-Series G30', 914);
insert into estacion (modelo, capacidad) values ('Skyhawk', 915);
insert into estacion (modelo, capacidad) values ('Sierra 2500', 916);
insert into estacion (modelo, capacidad) values ('Type 2', 917);
insert into estacion (modelo, capacidad) values ('Daewoo Lacetti', 918);
insert into estacion (modelo, capacidad) values ('Lancer Evolution', 919);
insert into estacion (modelo, capacidad) values ('Challenger', 920);
insert into estacion (modelo, capacidad) values ('xD', 921);
insert into estacion (modelo, capacidad) values ('Voyager', 922);
insert into estacion (modelo, capacidad) values ('riolet', 923);
insert into estacion (modelo, capacidad) values ('Escape', 924);
insert into estacion (modelo, capacidad) values ('Range Rover Sport', 925);
insert into estacion (modelo, capacidad) values ('98', 926);
insert into estacion (modelo, capacidad) values ('Alero', 927);
insert into estacion (modelo, capacidad) values ('Mustang', 928);
insert into estacion (modelo, capacidad) values ('G6', 929);
insert into estacion (modelo, capacidad) values ('612 Scaglietti', 930);
insert into estacion (modelo, capacidad) values ('T100 Xtra', 931);
insert into estacion (modelo, capacidad) values ('90', 932);
insert into estacion (modelo, capacidad) values ('A6', 933);
insert into estacion (modelo, capacidad) values ('Rodeo', 934);
insert into estacion (modelo, capacidad) values ('Continental', 935);
insert into estacion (modelo, capacidad) values ('Relay', 936);
insert into estacion (modelo, capacidad) values ('Tundra', 937);
insert into estacion (modelo, capacidad) values ('Alero', 938);
insert into estacion (modelo, capacidad) values ('6 Series', 939);
insert into estacion (modelo, capacidad) values ('LeMans', 940);
insert into estacion (modelo, capacidad) values ('Continental Super', 941);
insert into estacion (modelo, capacidad) values ('Outback', 942);
insert into estacion (modelo, capacidad) values ('Corrado', 943);
insert into estacion (modelo, capacidad) values ('Grand Vitara', 944);
insert into estacion (modelo, capacidad) values ('Odyssey', 945);
insert into estacion (modelo, capacidad) values ('Navajo', 946);
insert into estacion (modelo, capacidad) values ('Regal', 947);
insert into estacion (modelo, capacidad) values ('SLK-Class', 948);
insert into estacion (modelo, capacidad) values ('Canyon', 949);
insert into estacion (modelo, capacidad) values ('Mark VIII', 950);
insert into estacion (modelo, capacidad) values ('9-2X', 951);
insert into estacion (modelo, capacidad) values ('Suburban 2500', 952);
insert into estacion (modelo, capacidad) values ('Tacoma', 953);
insert into estacion (modelo, capacidad) values ('Escort', 954);
insert into estacion (modelo, capacidad) values ('Vantage', 955);
insert into estacion (modelo, capacidad) values ('Gallardo', 956);
insert into estacion (modelo, capacidad) values ('ES', 957);
insert into estacion (modelo, capacidad) values ('330', 958);
insert into estacion (modelo, capacidad) values ('XK', 959);
insert into estacion (modelo, capacidad) values ('MPV', 960);
insert into estacion (modelo, capacidad) values ('Capri', 961);
insert into estacion (modelo, capacidad) values ('Cabriolet', 962);
insert into estacion (modelo, capacidad) values ('Golf', 963);
insert into estacion (modelo, capacidad) values ('E-Series', 964);
insert into estacion (modelo, capacidad) values ('Escape', 965);
insert into estacion (modelo, capacidad) values ('Wrangler', 966);
insert into estacion (modelo, capacidad) values ('Tucson', 967);
insert into estacion (modelo, capacidad) values ('Rally Wagon 3500', 968);
insert into estacion (modelo, capacidad) values ('Mirage', 969);
insert into estacion (modelo, capacidad) values ('Expedition', 970);
insert into estacion (modelo, capacidad) values ('Eldorado', 971);
insert into estacion (modelo, capacidad) values ('Civic', 972);
insert into estacion (modelo, capacidad) values ('Avenger', 973);
insert into estacion (modelo, capacidad) values ('S60', 974);
insert into estacion (modelo, capacidad) values ('Tredia', 975);
insert into estacion (modelo, capacidad) values ('Cabriolet', 976);
insert into estacion (modelo, capacidad) values ('Chevette', 977);
insert into estacion (modelo, capacidad) values ('Paseo', 978);
insert into estacion (modelo, capacidad) values ('H1', 979);
insert into estacion (modelo, capacidad) values ('Parisienne', 980);
insert into estacion (modelo, capacidad) values ('Routan', 981);
insert into estacion (modelo, capacidad) values ('QX', 982);
insert into estacion (modelo, capacidad) values ('Sebring', 983);
insert into estacion (modelo, capacidad) values ('5 Series', 984);
insert into estacion (modelo, capacidad) values ('Spyder', 985);
insert into estacion (modelo, capacidad) values ('Camry', 986);
insert into estacion (modelo, capacidad) values ('Five Hundred', 987);
insert into estacion (modelo, capacidad) values ('1 Series', 988);
insert into estacion (modelo, capacidad) values ('3500', 989);
insert into estacion (modelo, capacidad) values ('GTO', 990);
insert into estacion (modelo, capacidad) values ('Commander', 991);
insert into estacion (modelo, capacidad) values ('530', 992);
insert into estacion (modelo, capacidad) values ('A8', 993);
insert into estacion (modelo, capacidad) values ('Solara', 994);
insert into estacion (modelo, capacidad) values ('L-Series', 995);
insert into estacion (modelo, capacidad) values ('Explorer', 996);
insert into estacion (modelo, capacidad) values ('Patriot', 997);
insert into estacion (modelo, capacidad) values ('850', 998);
insert into estacion (modelo, capacidad) values ('Civic GX', 999);
insert into estacion (modelo, capacidad) values ('Tucson', 1000);
