insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (196, 785, 'Iguana, marine');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (576, 917, 'Australian masked owl');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (683, 300, 'Dove, rock');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (315, 778, 'Goanna lizard');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (379, 751, 'Bushpig');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (4, 573, 'Hoary marmot');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (997, 305, 'Turtle, snake-necked');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (26, 210, 'Antechinus, brown');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (189, 131, 'Gull, pacific');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (352, 821, 'Skimmer, four-spotted');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (396, 199, 'Alpaca');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (631, 448, 'Jacana, african');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (735, 807, 'Southern lapwing');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (518, 967, 'Toddy cat');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (973, 557, 'Cat, civet');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (831, 249, 'Cat, civet');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (941, 82, 'Dove, white-winged');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (256, 181, 'Royal tern');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (553, 859, 'Baboon, chacma');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (711, 497, 'Yellow-necked spurfowl');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (524, 627, 'Grey phalarope');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (957, 228, 'Javanese cormorant');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (504, 197, 'Bee-eater, white-fronted');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (774, 528, 'North American red fox');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (212, 216, 'Common seal');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (456, 84, 'Tortoise, asian foreset');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (115, 98, 'Blacksmith plover');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (23, 626, 'Coyote');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (323, 145, 'Gerbil (unidentified)');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (899, 765, 'Dragonfly, russian');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (428, 473, 'Frog (unidentified)');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (130, 497, 'Paca');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (242, 542, 'Blue peacock');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (848, 906, 'Rufous tree pie');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (761, 701, 'Long-nosed bandicoot');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (8, 502, 'Common goldeneye');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (693, 615, 'Palm squirrel');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (343, 931, 'Two-toed sloth');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (28, 963, 'Weaver, sociable');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (347, 89, 'Yellow-bellied marmot');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (360, 288, 'Gemsbok');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (663, 962, 'Turtle, snake-necked');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (586, 626, 'Hawk, galapagos');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (970, 224, 'Crane, blue');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (217, 302, 'Jackal, golden');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (782, 286, 'Phalarope, red');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (487, 57, 'Asian water dragon');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (436, 905, 'Uinta ground squirrel');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (96, 235, 'Squirrel, grey-footed');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (299, 793, 'Alligator, mississippi');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (768, 866, 'North American beaver');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (546, 233, 'Red deer');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (358, 867, 'Wolf, mexican');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (551, 341, 'Puma');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (37, 333, 'Sidewinder');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (545, 277, 'White-tailed jackrabbit');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (733, 920, 'Moorhen, purple');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (689, 386, 'Tortoise, burmese brown mountain');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (580, 6, 'Squirrel, pine');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (873, 484, 'Duck, blue');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (468, 221, 'Hummingbird (unidentified)');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (729, 245, 'Blue-tongued lizard');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (429, 171, 'Common goldeneye');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (791, 101, 'Seal, northern elephant');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (987, 245, 'Sidewinder');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (140, 62, 'Hottentot teal');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (548, 244, 'Deer, roe');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (736, 629, 'Seal, harbor');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (570, 882, 'Jackal, silver-backed');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (323, 330, 'Stanley crane');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (926, 858, 'Common langur');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (690, 635, 'Deer, savannah');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (136, 617, 'White-browed sparrow weaver');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (126, 763, 'Spider, wolf');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (60, 929, 'Bohor reedbuck');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (171, 806, 'Steenbuck');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (50, 524, 'Ferret, black-footed');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (786, 59, 'Blacksmith plover');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (706, 786, 'Sarus crane');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (430, 47, 'Otter, north american river');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (335, 936, 'Oribi');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (251, 929, 'Woodcock, american');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (819, 512, 'Western pygmy possum');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (138, 195, 'Goldeneye, barrows');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (369, 291, 'Giant otter');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (833, 766, 'Heron, grey');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (616, 105, 'European beaver');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (96, 418, 'Little brown dove');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (734, 451, 'Bulbul, black-fronted');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (798, 348, 'Capuchin, black-capped');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (390, 968, 'Porcupine, prehensile-tailed');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (370, 919, 'Eurasian beaver');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (521, 769, 'Magistrate black colobus');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (533, 372, 'Tiger');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (708, 246, 'Royal tern');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (78, 292, 'Fox, silver-backed');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (487, 285, 'White-fronted capuchin');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (224, 696, 'Tortoise, radiated');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (160, 766, 'Hottentot teal');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (809, 62, 'Stork, jabiru');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (188, 369, 'Indian porcupine');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (484, 363, 'Fork-tailed drongo');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (636, 993, 'Rattlesnake, dusky');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (916, 670, 'Striped dolphin');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (210, 901, 'Owl, white-browed');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (640, 793, 'Marten, american');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (31, 848, 'Trumpeter, green-winged');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (952, 10, 'Hare, arctic');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (78, 534, 'American black bear');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (102, 813, 'Hawk-eagle, crowned');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (847, 95, 'Caracara, yellow-headed');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (839, 674, 'Pale white-eye');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (827, 772, 'Baboon, gelada');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (340, 952, 'Wolf, mexican');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (835, 168, 'Heron, yellow-crowned night');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (224, 346, 'Japanese macaque');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (634, 80, 'Phascogale, brush-tailed');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (253, 529, 'Ibis, puna');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (797, 603, 'Crested porcupine');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (100, 716, 'Little grebe');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (371, 388, 'Aardwolf');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (786, 661, 'Porcupine, north american');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (634, 177, 'Stork, marabou');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (273, 27, 'Trumpeter swan');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (223, 631, 'Grenadier, common');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (97, 777, 'Black swan');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (22, 346, 'Pie, rufous tree');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (283, 398, 'Ground legaan');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (944, 144, 'White-tailed deer');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (679, 102, 'Gemsbok');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (94, 122, 'Squirrel, golden-mantled ground');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (484, 228, 'Bee-eater, nubian');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (108, 959, 'Blackish oystercatcher');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (123, 954, 'Common raccoon');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (762, 548, 'Seal, northern fur');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (170, 814, 'Deer, spotted');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (291, 436, 'Leopard, indian');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (796, 418, 'Ant (unidentified)');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (141, 821, 'Crane, sarus');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (394, 43, 'Lizard, collared');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (759, 536, 'Indian jackal');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (824, 273, 'Paddy heron (unidentified)');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (817, 813, 'Vulture, white-headed');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (35, 1000, 'White-fronted capuchin');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (360, 744, 'Bee-eater (unidentified)');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (423, 367, 'Square-lipped rhinoceros');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (410, 561, 'Snake-necked turtle');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (52, 384, 'Screamer, southern');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (58, 534, 'Magellanic penguin');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (778, 628, 'Long-finned pilot whale');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (510, 411, 'Kangaroo, brush-tailed rat');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (595, 924, 'Southern elephant seal');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (323, 685, 'Deer, black-tailed');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (592, 679, 'Galapagos tortoise');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (372, 881, 'Langur, hanuman');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (337, 64, 'Squirrel glider');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (36, 439, 'Golden jackal');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (688, 995, 'Crane, black-crowned');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (780, 498, 'Southern lapwing');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (330, 422, 'Grey mouse lemur');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (660, 269, 'Glossy starling (unidentified)');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (378, 290, 'Bat-eared fox');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (88, 398, 'Badger, american');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (245, 701, 'Alligator, american');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (423, 160, 'Gray heron');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (607, 923, 'Carpet snake');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (788, 401, 'Golden-mantled ground squirrel');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (430, 273, 'Baleen whale');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (312, 292, 'Square-lipped rhinoceros');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (770, 951, 'Pampa gray fox');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (27, 852, 'Burrowing owl');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (442, 952, 'Eland, common');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (72, 14, 'Weaver, white-browed sparrow');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (6, 587, 'Green-backed heron');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (36, 635, 'Kite, black');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (815, 727, 'Fork-tailed drongo');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (321, 214, 'Shrike, crimson-breasted');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (392, 815, 'Argalis');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (418, 966, 'Honey badger');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (958, 178, 'Waxbill, blue');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (621, 911, 'Crane, sarus');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (103, 141, 'White-winged black tern');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (110, 450, 'Grenadier, purple');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (68, 507, 'Emerald-spotted wood dove');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (609, 895, 'Tinamou, elegant crested');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (883, 73, 'Drongo, fork-tailed');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (355, 697, 'Crested screamer');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (124, 155, 'Dingo');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (664, 150, 'Deer, barasingha');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (124, 32, 'Peacock, indian');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (2, 63, 'Dik, kirk''s dik');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (940, 203, 'Green-winged trumpeter');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (900, 633, 'Southern lapwing');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (578, 278, 'Wolf, mexican');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (861, 172, 'Mouse, four-striped grass');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (445, 69, 'Tawny frogmouth');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (920, 800, 'Field flicker');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (30, 486, 'Asian elephant');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (835, 401, 'Blue-tongued skink');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (911, 100, 'Large cormorant');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (919, 196, 'Hyena, brown');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (979, 469, 'Cat, jungle');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (172, 529, 'Cape starling');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (249, 55, 'Blue peacock');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (789, 857, 'Kinkajou');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (579, 899, 'African bush squirrel');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (584, 743, 'Eland, common');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (456, 779, 'Fringe-eared oryx');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (12, 677, 'Kite, black');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (220, 233, 'Monkey, black spider');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (151, 565, 'Tenrec, tailless');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (109, 170, 'Bird, secretary');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (72, 907, 'Lion, california sea');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (104, 375, 'Puku');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (163, 31, 'Toucan, white-throated');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (580, 295, 'Rat, desert kangaroo');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (480, 646, 'Purple moorhen');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (389, 61, 'Red-billed buffalo weaver');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (870, 999, 'Nyala');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (413, 169, 'Pied avocet');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (432, 964, 'Gnu, brindled');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (433, 748, 'Beaver, american');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (334, 462, 'Turkey, wild');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (5, 34, 'Cobra, egyptian');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (143, 38, 'Deer, white-tailed');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (323, 806, 'Barking gecko');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (741, 612, 'Magpie, black-backed');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (990, 734, 'Tinamou, elegant crested');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (738, 818, 'Red-capped cardinal');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (228, 665, 'Fox, bat-eared');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (748, 465, 'Red meerkat');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (134, 925, 'Common palm civet');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (144, 635, 'Mexican boa');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (25, 496, 'Great kiskadee');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (602, 728, 'Greater kudu');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (998, 910, 'Rhinoceros, white');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (35, 50, 'Colobus, white-mantled');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (607, 946, 'Dabchick');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (864, 924, 'Monkey, black spider');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (343, 581, 'Elephant, african');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (867, 181, 'Gazer, sun');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (330, 619, 'Tortoise, asian foreset');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (933, 419, 'Gecko, ring-tailed');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (951, 759, 'Otter, canadian river');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (669, 192, 'Langur, gray');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (176, 30, 'American bighorn sheep');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (618, 286, 'Ring-tailed gecko');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (768, 455, 'Monkey, vervet');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (80, 719, 'American black bear');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (733, 332, 'Fox, arctic');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (255, 827, 'Black-eyed bulbul');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (378, 719, 'Ibex');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (708, 792, 'Mouflon');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (322, 386, 'Shrike, common boubou');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (962, 605, 'Red brocket');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (200, 185, 'Denham''s bustard');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (930, 332, 'Blue shark');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (976, 440, 'Jaguarundi');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (851, 970, 'Black kite');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (623, 741, 'Kangaroo, brush-tailed rat');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (158, 547, 'Mongoose, eastern dwarf');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (30, 716, 'Sidewinder');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (829, 672, 'Spectacled caiman');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (701, 743, 'Canada goose');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (711, 874, 'Caribou');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (311, 160, 'Red-capped cardinal');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (836, 619, 'Bateleur eagle');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (125, 356, 'Common duiker');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (881, 519, 'Warthog');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (832, 550, 'Python, carpet');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (579, 913, 'Water monitor');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (931, 942, 'Marmot, yellow-bellied');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (803, 765, 'Tern, white-winged');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (279, 862, 'Black-faced kangaroo');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (446, 707, 'Southern ground hornbill');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (633, 639, 'Snowy owl');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (729, 47, 'Crown of thorns starfish');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (348, 445, 'Hen, sage');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (559, 830, 'Squirrel, uinta ground');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (647, 836, 'Two-toed tree sloth');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (125, 354, 'Alpaca');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (794, 776, 'Stork, jabiru');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (619, 298, 'Mongoose, small indian');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (34, 458, 'Miner''s cat');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (53, 612, 'Burmese black mountain tortoise');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (851, 808, 'Grizzly bear');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (601, 524, 'Mongoose, yellow');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (952, 917, 'Brown antechinus');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (592, 670, 'Pallas''s fish eagle');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (782, 135, 'Red meerkat');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (436, 390, 'Common waterbuck');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (138, 289, 'Bison, american');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (449, 335, 'Red-winged blackbird');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (467, 451, 'Russian dragonfly');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (921, 126, 'Red brocket');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (97, 332, 'Emu');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (676, 966, 'Square-lipped rhinoceros');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (327, 774, 'Javan gold-spotted mongoose');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (461, 535, 'Waterbuck, defassa');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (129, 501, 'Greater flamingo');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (858, 754, 'Elk, Wapiti');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (73, 123, 'Baboon, chacma');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (697, 528, 'Fox, grey');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (859, 659, 'White-rumped vulture');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (497, 975, 'Beaver, american');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (407, 323, 'Capuchin, white-fronted');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (743, 784, 'Red-legged pademelon');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (730, 95, 'Swan, black');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (710, 756, 'Otter, giant');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (765, 440, 'Shrew, mandras tree');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (565, 47, 'Springbok');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (554, 396, 'Lava gull');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (777, 602, 'Peccary, collared');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (216, 924, 'Jackal, black-backed');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (572, 951, 'Red-legged pademelon');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (305, 988, 'Macaque, bonnet');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (651, 331, 'Magellanic penguin');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (6, 869, 'Gazelle, thomson''s');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (345, 718, 'Blue peacock');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (581, 383, 'Cormorant, large');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (78, 53, 'Reindeer');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (858, 136, 'Eastern fox squirrel');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (854, 60, 'Margay');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (184, 200, 'Antelope, four-horned');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (975, 481, 'Musk ox');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (460, 966, 'Sandpiper, spotted wood');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (52, 519, 'Golden eagle');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (827, 969, 'Gray heron');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (325, 935, 'Monitor, two-banded');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (176, 683, 'Ibis, puna');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (350, 457, 'Penguin, galapagos');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (989, 842, 'Gull, silver');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (817, 81, 'Hoopoe, eurasian');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (382, 599, 'Dolphin, bottle-nose');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (538, 927, 'White rhinoceros');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (467, 243, 'Shrike, crimson-breasted');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (606, 563, 'Striped skunk');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (801, 35, 'Cook''s tree boa');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (969, 92, 'Bat, asian false vampire');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (729, 921, 'Blue catfish');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (316, 48, 'Brocket, red');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (679, 990, 'Klipspringer');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (209, 991, 'Gray rhea');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (576, 143, 'Lizard, collared');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (972, 790, 'Mountain goat');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (591, 979, 'Red lava crab');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (796, 494, 'Steenbuck');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (129, 836, 'Pallas''s fish eagle');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (480, 374, 'Chipmunk, least');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (618, 942, 'Kirk''s dik dik');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (408, 602, 'Tayra');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (986, 611, 'Screamer, crested');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (162, 264, 'Hartebeest, red');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (866, 213, 'Red howler monkey');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (841, 431, 'Camel, dromedary');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (83, 758, 'Mountain goat');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (457, 798, 'Antelope, roan');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (335, 892, 'Macaque, bonnet');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (361, 63, 'Squirrel, european red');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (876, 297, 'Jackal, asiatic');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (880, 272, 'Brush-tailed rat kangaroo');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (310, 147, 'Shrike, common boubou');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (931, 100, 'Bustard, stanley');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (283, 460, 'Otter, african clawless');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (306, 385, 'Whale, killer');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (72, 790, 'American woodcock');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (134, 783, 'White-throated toucan');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (315, 393, 'Common zebra');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (655, 782, 'Madagascar hawk owl');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (45, 288, 'Possum, common brushtail');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (13, 397, 'Bird, pied butcher');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (745, 297, 'White-nosed coatimundi');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (619, 874, 'Asian red fox');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (949, 783, 'Pie, indian tree');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (935, 634, 'Mockingbird, galapagos');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (303, 432, 'Squirrel, eastern fox');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (966, 557, 'Indian peacock');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (989, 363, 'Four-horned antelope');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (917, 912, 'Savannah deer (unidentified)');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (740, 201, 'Lourie, grey');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (999, 112, 'Toddy cat');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (660, 249, 'Laughing kookaburra');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (201, 741, 'Tyrant flycatcher');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (643, 926, 'Common pheasant');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (799, 373, 'Turkey, wild');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (810, 475, 'Goose, cereopsis');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (687, 232, 'Langur, hanuman');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (733, 805, 'Glider, feathertail');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (865, 934, 'Cat, kaffir');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (66, 633, 'Canadian tiger swallowtail butterfly');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (656, 429, 'Dragon, komodo');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (697, 544, 'Bird, magnificent frigate');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (237, 112, 'White-tailed jackrabbit');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (482, 533, 'Pied crow');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (672, 260, 'Swainson''s francolin');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (213, 79, 'Red-necked phalarope');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (565, 210, 'Sable antelope');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (658, 847, 'Paca');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (892, 19, 'Clark''s nutcracker');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (259, 176, 'Crown of thorns starfish');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (24, 726, 'Black-capped chickadee');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (883, 735, 'Tayra');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (836, 739, 'Peacock, blue');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (736, 353, 'Blackbuck');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (32, 90, 'Denham''s bustard');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (48, 882, 'Nubian bee-eater');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (41, 953, 'Crested bunting');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (472, 586, 'Levaillant''s barbet');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (206, 540, 'Tortoise, radiated');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (877, 804, 'Penguin, fairy');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (877, 744, 'Macaque, pig-tailed');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (524, 674, 'Penguin, galapagos');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (778, 810, 'Barasingha deer');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (144, 982, 'Caribou');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (564, 123, 'Tortoise, burmese black mountain');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (654, 859, 'Tawny eagle');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (675, 207, 'Thrasher, curve-billed');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (115, 670, 'American badger');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (876, 529, 'Long-tailed jaeger');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (239, 687, 'Sheathbill, snowy');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (103, 493, 'Brown hyena');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (922, 832, 'Striped skunk');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (862, 184, 'Wallaby, bennett''s');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (448, 337, 'Trotter, lily');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (403, 320, 'Bleeding heart monkey');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (399, 167, 'Green-winged trumpeter');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (232, 93, 'Macaque, pig-tailed');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (43, 183, 'Coatimundi, white-nosed');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (306, 336, 'Bulbul, black-fronted');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (40, 203, 'Grizzly bear');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (550, 169, 'Dog, bush');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (168, 572, 'Rhesus macaque');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (962, 832, 'Tayra');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (874, 178, 'Vicuna');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (637, 226, 'White-tailed deer');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (584, 186, 'Porcupine, african');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (65, 948, 'Desert spiny lizard');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (99, 361, 'Common langur');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (843, 251, 'Burchell''s gonolek');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (714, 563, 'Swan, trumpeter');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (71, 983, 'White-tailed deer');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (416, 611, 'Goanna lizard');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (953, 920, 'Bushpig');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (90, 553, 'Quoll, eastern');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (931, 520, 'Large-eared bushbaby');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (739, 285, 'Dabchick');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (969, 858, 'Mudskipper (unidentified)');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (225, 722, 'Royal tern');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (918, 954, 'Peacock, blue');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (298, 339, 'Caribou');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (968, 482, 'Sage grouse');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (349, 640, 'Kiskadee, great');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (121, 848, 'Raven, cape');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (921, 589, 'Goose, cereopsis');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (724, 803, 'Asian foreset tortoise');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (120, 667, 'African porcupine');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (309, 147, 'Lorikeet, scaly-breasted');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (862, 389, 'Crimson-breasted shrike');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (77, 21, 'Wapiti, elk,');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (254, 779, 'Desert kangaroo rat');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (669, 738, 'Cape white-eye');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (609, 500, 'Southern sea lion');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (185, 14, 'Whale, killer');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (494, 443, 'Bustard, denham''s');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (560, 589, 'Phalarope, northern');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (475, 628, 'Egyptian vulture');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (93, 945, 'Southern brown bandicoot');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (87, 133, 'Giant heron');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (15, 332, 'Parakeet, rose-ringed');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (687, 525, 'Trotter, lily');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (297, 18, 'Coke''s hartebeest');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (983, 490, 'Kookaburra, laughing');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (138, 380, 'Great white pelican');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (995, 888, 'Golden brush-tailed possum');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (716, 24, 'Australian pelican');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (67, 464, 'Mynah, indian');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (883, 132, 'Blue shark');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (596, 798, 'Wallaroo, common');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (762, 794, 'Hyrax');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (644, 407, 'Dove, rock');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (931, 103, 'Bee-eater, white-fronted');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (617, 474, 'Agouti');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (788, 579, 'Lory, rainbow');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (600, 654, 'Monster, gila');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (158, 183, 'Oribi');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (230, 289, 'Bent-toed gecko');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (107, 824, 'Heron, yellow-crowned night');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (942, 511, 'Crown of thorns starfish');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (184, 185, 'Dragon, netted rock');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (316, 711, 'Desert spiny lizard');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (872, 429, 'North American red fox');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (523, 531, 'Goose, canada');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (568, 485, 'Dog, bush');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (508, 810, 'Grouse, sage');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (859, 551, 'Owl, great horned');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (715, 136, 'Pelican, brown');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (69, 979, 'Dove, white-winged');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (640, 737, 'Fox, asian red');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (881, 986, 'Netted rock dragon');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (751, 492, 'Nile crocodile');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (90, 519, 'Emerald-spotted wood dove');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (139, 432, 'Rabbit, eastern cottontail');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (434, 477, 'Southern elephant seal');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (328, 896, 'Stick insect');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (66, 317, 'Golden jackal');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (293, 558, 'Marabou stork');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (12, 612, 'Bird, secretary');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (531, 766, 'Bat, madagascar fruit');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (64, 341, 'Warthog');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (75, 796, 'Lesser mouse lemur');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (202, 661, 'Sea birds (unidentified)');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (471, 969, 'Heron, striated');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (543, 357, 'Grouse, sage');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (144, 967, 'Buffalo, wild water');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (488, 751, 'Black-crowned crane');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (51, 511, 'Savannah deer (unidentified)');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (568, 445, 'Fox, crab-eating');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (505, 23, 'Otter, brazilian');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (145, 298, 'Stork, greater adjutant');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (46, 587, 'Polar bear');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (347, 705, 'Frogmouth, tawny');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (164, 360, 'Beaver, eurasian');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (257, 900, 'Cat, ringtail');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (623, 242, 'Bleu, blue-breasted cordon');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (602, 277, 'Stork, european');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (192, 182, 'Waxbill, violet-eared');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (692, 707, 'Australian spiny anteater');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (908, 500, 'Coqui partridge');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (408, 506, 'Pine snake (unidentified)');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (785, 966, 'American beaver');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (253, 830, 'Paca');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (80, 296, 'Pheasant, ring-necked');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (942, 460, 'Common genet');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (132, 944, 'Bear, black');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (972, 19, 'African wild cat');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (804, 104, 'Cockatoo, red-tailed');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (268, 534, 'Sparrow, house');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (375, 278, 'Verreaux''s sifaka');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (519, 677, 'Fox, asian red');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (489, 989, 'Waterbuck, common');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (8, 235, 'Flightless cormorant');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (916, 509, 'Shrew, mandras tree');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (757, 721, 'Weaver, sociable');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (75, 118, 'Egyptian cobra');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (311, 885, 'Gull, silver');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (585, 890, 'Herring gull');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (131, 209, 'Greylag goose');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (165, 501, 'Musk ox');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (915, 867, 'Otter, brazilian');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (727, 65, 'Chickadee, black-capped');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (761, 303, 'Caracara (unidentified)');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (641, 485, 'Eagle, pallas''s fish');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (416, 860, 'Chickadee, black-capped');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (841, 978, 'Caribou');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (108, 902, 'Sparrow, rufous-collared');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (585, 188, 'King cormorant');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (840, 303, 'Turkey, common');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (776, 878, 'Lemming, arctic');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (845, 609, 'Brown and yellow marshbird');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (412, 341, 'Spoonbill, european');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (983, 757, 'Common turkey');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (765, 136, 'American marten');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (702, 817, 'Canadian tiger swallowtail butterfly');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (107, 325, 'Field flicker');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (210, 249, 'Avocet, pied');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (124, 599, 'Snake, green vine');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (969, 609, 'Pied butcher bird');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (932, 622, 'Plover, three-banded');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (52, 831, 'Rainbow lory');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (897, 227, 'Tinamou, elegant crested');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (271, 205, 'Cardinal, red-capped');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (922, 461, 'Small-clawed otter');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (710, 398, 'Cape fox');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (651, 395, 'Chacma baboon');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (630, 786, 'Stilt, black-winged');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (505, 190, 'Burmese brown mountain tortoise');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (896, 456, 'Goose, knob-nosed');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (682, 339, 'Polecat, african');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (651, 798, 'Bahama pintail');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (527, 504, 'Mexican wolf');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (286, 715, 'Kangaroo, jungle');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (460, 963, 'American crow');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (386, 329, 'Silver-backed jackal');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (613, 412, 'African wild cat');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (589, 25, 'Bee-eater (unidentified)');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (386, 401, 'Cattle egret');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (146, 422, 'Ornate rock dragon');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (419, 301, 'Black-tailed deer');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (463, 569, 'Thrasher, curve-billed');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (771, 689, 'Boat-billed heron');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (739, 125, 'Possum, pygmy');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (661, 32, 'Tern, arctic');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (164, 300, 'Genet, small-spotted');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (631, 857, 'Grey mouse lemur');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (249, 812, 'Colobus, black and white');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (155, 466, 'Red meerkat');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (941, 181, 'Pronghorn');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (431, 366, 'Fox, asian red');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (443, 925, 'Sungazer, yellow-brown');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (146, 293, 'Asian water buffalo');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (992, 163, 'Impala');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (523, 442, 'Arctic ground squirrel');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (278, 110, 'Sambar');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (936, 622, 'Lily trotter');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (596, 794, 'American crow');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (655, 250, 'Capuchin, white-fronted');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (5, 954, 'Lion, south american sea');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (781, 798, 'Hudsonian godwit');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (44, 550, 'Madagascar fruit bat');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (300, 661, 'Eastern grey kangaroo');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (463, 604, 'Pig-tailed macaque');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (477, 981, 'Tinamou, elegant crested');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (2, 984, 'River wallaby');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (442, 962, 'Tarantula, salmon pink bird eater');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (748, 456, 'Porcupine, crested');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (473, 960, 'Ibex');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (342, 920, 'Stork, black-necked');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (348, 667, 'Long-tailed skua');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (406, 72, 'Ferret, black-footed');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (587, 809, 'Gull, swallow-tail');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (822, 141, 'Squirrel, african bush');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (838, 839, 'Crane, brolga');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (852, 175, 'African lynx');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (7, 774, 'Oribi');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (592, 580, 'Heron, little');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (110, 32, 'Sambar');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (833, 568, 'Weaver, white-browed sparrow');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (917, 432, 'Zebra, common');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (347, 739, 'Flamingo, lesser');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (514, 435, 'Sifaka, verreaux''s');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (465, 737, 'Great white pelican');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (732, 573, 'Weaver, red-billed buffalo');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (442, 706, 'Aardwolf');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (919, 248, 'Grey mouse lemur');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (960, 823, 'Pelican, eastern white');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (527, 990, 'Eagle, long-crested hawk');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (336, 772, 'Spotted wood sandpiper');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (509, 463, 'Long-tailed spotted cat');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (122, 989, 'Cormorant, javanese');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (221, 551, 'Monkey, rhesus');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (49, 526, 'Yellow mongoose');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (4, 520, 'Fringe-eared oryx');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (93, 283, 'Stork, european');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (363, 789, 'Wild boar');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (129, 519, 'South American puma');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (502, 249, 'Brown pelican');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (342, 855, 'Gecko, bent-toed');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (410, 742, 'Crab, red lava');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (657, 41, 'Seal, harbor');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (76, 859, 'Lizard (unidentified)');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (766, 545, 'Kori bustard');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (150, 114, 'Macaw, green-winged');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (427, 156, 'Cereopsis goose');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (438, 26, 'Snowy egret');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (412, 112, 'Gull, dusky');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (121, 360, 'Crane, wattled');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (43, 39, 'Squirrel glider');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (251, 398, 'Arboral spiny rat');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (220, 591, 'Zebra, common');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (187, 122, 'Great white pelican');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (296, 980, 'Brolga crane');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (985, 594, 'Red phalarope');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (262, 251, 'Sifaka, verreaux''s');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (776, 986, 'Spurfowl, yellow-necked');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (685, 269, 'European shelduck');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (836, 823, 'Stork, saddle-billed');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (642, 37, 'Kelp gull');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (283, 328, 'Jackal, asiatic');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (135, 861, 'Red brocket');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (531, 539, 'Viper, egyptian');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (291, 28, 'Vulture, white-headed');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (499, 40, 'Duiker, common');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (713, 217, 'Giant girdled lizard');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (930, 806, 'Squirrel, palm');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (381, 529, 'Black-throated cardinal');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (451, 147, 'Armadillo, nine-banded');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (836, 165, 'Opossum, american virginia');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (264, 285, 'Little heron');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (854, 403, 'Killer whale');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (242, 339, 'Brown capuchin');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (184, 668, 'Oriental white-backed vulture');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (672, 231, 'Water legaan');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (797, 715, 'American crow');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (743, 118, 'Common palm civet');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (386, 464, 'Wallaby, euro');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (210, 152, 'Flying fox (unidentified)');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (507, 444, 'Red phalarope');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (314, 303, 'Partridge, coqui');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (439, 542, 'Grouse, greater sage');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (801, 105, 'Coqui francolin');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (583, 311, 'Southern boubou');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (774, 212, 'Duck, blue');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (906, 899, 'Cormorant, javanese');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (301, 707, 'Vervet monkey');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (447, 563, 'Great kiskadee');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (556, 979, 'Nighthawk, common');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (115, 669, 'Giant otter');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (62, 450, 'Cat, civet');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (713, 144, 'Burchell''s gonolek');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (4, 727, 'Downy woodpecker');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (302, 586, 'Glider, sugar');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (168, 816, 'Possum, western pygmy');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (747, 859, 'Lemur, lesser mouse');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (249, 472, 'Southern elephant seal');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (183, 345, 'Antelope, sable');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (565, 431, 'Ornate rock dragon');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (429, 527, 'Common langur');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (290, 910, 'Phalarope, red');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (576, 996, 'Mouse, four-striped grass');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (36, 974, 'Blackish oystercatcher');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (821, 534, 'Black-footed ferret');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (719, 914, 'Sally lightfoot crab');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (546, 533, 'Porcupine, crested');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (790, 571, 'Moose');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (331, 295, 'Lemur, lesser mouse');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (443, 395, 'Spoonbill, white');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (697, 835, 'Heron, striated');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (672, 676, 'Skink, blue-tongued');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (293, 773, 'Vulture, lappet-faced');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (538, 416, 'Stanley bustard');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (581, 839, 'Western grey kangaroo');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (431, 489, 'Golden eagle');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (924, 674, 'Fat-tailed dunnart');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (637, 180, 'Springhare');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (239, 256, 'Woylie');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (874, 413, 'Red-knobbed coot');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (948, 116, 'Buffalo, asian water');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (982, 767, 'Squirrel, eastern fox');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (561, 245, 'Bustard, denham''s');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (27, 438, 'Western bearded dragon');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (834, 735, 'Bear, black');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (305, 47, 'Worm snake (unidentified)');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (603, 614, 'Openbill, asian');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (607, 360, 'Common genet');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (748, 93, 'Lesser flamingo');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (612, 509, 'Langur, gray');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (513, 379, 'Asian false vampire bat');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (149, 670, 'African polecat');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (987, 7, 'Common boubou shrike');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (912, 3, 'Flying fox (unidentified)');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (287, 138, 'Yellow-brown sungazer');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (11, 685, 'Bare-faced go away bird');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (752, 905, 'Galapagos hawk');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (860, 733, 'Crab-eating raccoon');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (963, 502, 'Buffalo, american');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (65, 630, 'Fox, bat-eared');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (266, 508, 'Snowy owl');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (172, 356, 'Cobra, cape');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (971, 278, 'Woodchuck');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (932, 225, 'Ass, asiatic wild');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (91, 830, 'African porcupine');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (291, 977, 'Southern tamandua');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (214, 469, 'Uinta ground squirrel');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (792, 593, 'Wallaby, euro');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (250, 326, 'Lily trotter');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (221, 753, 'Whale, killer');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (470, 848, 'American crow');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (393, 395, 'Vulture, white-headed');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (800, 152, 'Reindeer');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (36, 306, 'Rock dove');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (840, 58, 'Superb starling');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (225, 522, 'Dove, mourning collared');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (775, 100, 'Long-crested hawk eagle');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (30, 894, 'Red and blue macaw');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (972, 790, 'Deer, white-tailed');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (963, 622, 'Eagle, golden');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (467, 763, 'Japanese macaque');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (297, 955, 'Mara');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (645, 198, 'Vulture, egyptian');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (187, 989, 'American Virginia opossum');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (108, 818, 'Kelp gull');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (101, 738, 'Brindled gnu');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (880, 470, 'Numbat');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (373, 863, 'Desert tortoise');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (408, 421, 'Nilgai');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (119, 34, 'Jackal, asiatic');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (927, 548, 'Lion, australian sea');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (504, 411, 'American Virginia opossum');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (550, 192, 'Jaeger, long-tailed');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (243, 169, 'Yellow-headed caracara');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (793, 146, 'Tern, white-winged black');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (219, 807, 'Squirrel, eurasian red');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (679, 47, 'Vulture, bengal');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (709, 255, 'Coqui partridge');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (91, 516, 'American buffalo');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (996, 788, 'Skimmer, four-spotted');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (231, 187, 'Mongoose, javan gold-spotted');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (278, 402, 'Squirrel, pine');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (531, 739, 'Puma');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (179, 964, 'Tiger snake');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (647, 809, 'Red-breasted cockatoo');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (378, 406, 'Emu');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (570, 988, 'White spoonbill');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (210, 870, 'Red lava crab');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (498, 313, 'American racer');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (109, 108, 'Monkey, rhesus');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (869, 652, 'Hanuman langur');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (818, 351, 'Glider, feathertail');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (733, 814, 'Meerkat, red');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (589, 495, 'Hartebeest, red');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (553, 278, 'Mongoose, yellow');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (854, 557, 'Gull, pacific');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (774, 812, 'Southern sea lion');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (526, 843, 'Otter, brazilian');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (555, 677, 'Southern right whale');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (795, 164, 'American alligator');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (684, 800, 'Turtle, eastern box');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (445, 555, 'Secretary bird');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (950, 893, 'Cape clawless otter');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (492, 317, 'Rattlesnake, horned');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (559, 591, 'Coqui francolin');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (378, 249, 'Raccoon, crab-eating');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (921, 854, 'Asian red fox');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (60, 543, 'Fox, arctic');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (680, 241, 'Macaw, blue and gold');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (165, 419, 'Pelican, eastern white');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (399, 780, 'Screamer, southern');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (163, 643, 'African buffalo');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (16, 13, 'Woodpecker, red-headed');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (34, 892, 'Kingfisher, malachite');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (147, 819, 'Tern, white-winged black');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (586, 457, 'Mongoose, small indian');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (158, 734, 'Emu');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (416, 603, 'Genet, common');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (221, 246, 'Western spotted skunk');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (369, 652, 'Blue catfish');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (936, 544, 'Spotted wood sandpiper');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (486, 622, 'Swan, trumpeter');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (725, 855, 'Baboon, chacma');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (440, 758, 'Siskin, pine');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (268, 378, 'Bird, magnificent frigate');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (465, 327, 'Bee-eater, carmine');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (353, 56, 'Cat, european wild');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (921, 216, 'Egyptian viper');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (31, 621, 'Southern sea lion');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (343, 999, 'European stork');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (169, 212, 'Alligator, mississippi');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (538, 761, 'Dog, bush');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (765, 862, 'Langur, common');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (954, 49, 'Lion, southern sea');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (841, 892, 'Small-toothed palm civet');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (408, 217, 'Beaver, eurasian');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (722, 958, 'Eagle owl (unidentified)');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (855, 397, 'Cockatoo, slender-billed');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (745, 377, 'Andean goose');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (995, 615, 'Macaw, red and blue');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (893, 273, 'Prairie falcon');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (37, 59, 'Bird, bare-faced go away');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (598, 888, 'Kirk''s dik dik');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (726, 716, 'Superb starling');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (319, 311, 'Common dolphin');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (825, 210, 'Heron, little');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (927, 741, 'Starling, cape');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (421, 286, 'African elephant');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (570, 202, 'Turkey, australian brush');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (670, 669, 'Chilean flamingo');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (787, 736, 'African red-eyed bulbul');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (705, 644, 'Gelada baboon');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (741, 650, 'Otter, small-clawed');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (299, 324, 'Crab-eating raccoon');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (473, 319, 'Mountain lion');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (76, 514, 'Crane, wattled');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (278, 891, 'Brown brocket');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (435, 381, 'Civet cat');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (922, 674, 'Galapagos mockingbird');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (554, 861, 'Fox, bat-eared');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (127, 945, 'Starfish, crown of thorns');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (21, 969, 'Black-eyed bulbul');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (457, 740, 'Steller sea lion');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (283, 570, 'Dove, emerald-spotted wood');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (876, 435, 'Hartebeest, coke''s');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (465, 507, 'Ass, asiatic wild');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (511, 306, 'Malagasy ground boa');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (362, 474, 'Vulture, oriental white-backed');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (878, 455, 'Black bear');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (853, 806, 'Purple grenadier');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (753, 126, 'Pigeon, feral rock');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (273, 985, 'Common brushtail possum');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (253, 659, 'Eastern fox squirrel');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (910, 320, 'Bobcat');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (927, 572, 'Hedgehog, south african');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (596, 468, 'Yellow-crowned night heron');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (945, 220, 'Viper, egyptian');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (287, 780, 'Anteater, australian spiny');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (432, 62, 'Hawk, red-tailed');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (737, 745, 'Red-winged hawk (unidentified)');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (981, 92, 'Macaw, green-winged');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (316, 104, 'Malachite kingfisher');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (783, 94, 'Asian water buffalo');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (577, 91, 'Southern elephant seal');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (182, 388, 'Osprey');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (855, 810, 'Pocket gopher (unidentified)');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (115, 354, 'Capuchin, white-fronted');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (710, 270, 'Puna ibis');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (145, 404, 'Duck, white-faced whistling');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (796, 736, 'Bat-eared fox');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (363, 622, 'Turtle, snake-necked');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (890, 641, 'African buffalo');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (311, 10, 'Blackish oystercatcher');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (922, 269, 'Tawny frogmouth');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (239, 454, 'Miner''s cat');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (869, 380, 'Ring-tailed gecko');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (748, 93, 'Fringe-eared oryx');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (250, 547, 'Corella, long-billed');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (593, 157, 'Smith''s bush squirrel');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (457, 204, 'Dragon, komodo');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (117, 303, 'Iguana, common green');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (5, 412, 'Black-faced kangaroo');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (349, 989, 'Coke''s hartebeest');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (729, 662, 'Field flicker');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (781, 321, 'Raccoon dog');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (378, 374, 'Yellow-brown sungazer');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (745, 222, 'Shark, blue');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (31, 24, 'Beisa oryx');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (971, 31, 'Badger, eurasian');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (985, 692, 'Dove, emerald-spotted wood');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (756, 383, 'Egyptian goose');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (635, 407, 'Galah');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (616, 353, 'Cape fox');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (278, 271, 'Spectacled caiman');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (543, 229, 'Macaque, pig-tailed');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (23, 158, 'Saddle-billed stork');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (698, 683, 'Guanaco');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (156, 419, 'Springhare');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (673, 716, 'Gila monster');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (947, 305, 'Warthog');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (989, 231, 'Cat, native');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (879, 875, 'Buffalo, american');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (9, 424, 'Boubou, southern');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (349, 474, 'African black crake');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (13, 973, 'Red-headed woodpecker');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (762, 756, 'Lorikeet, scaly-breasted');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (488, 871, 'Salmon, sockeye');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (201, 617, 'Crab-eating fox');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (794, 903, 'Fairy penguin');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (617, 466, 'Hummingbird (unidentified)');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (30, 507, 'Fox, asian red');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (372, 484, 'Deer, savannah');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (870, 342, 'White-eye, cape');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (691, 788, 'Raven, white-necked');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (657, 814, 'Bear, grizzly');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (716, 705, 'Lapwing (unidentified)');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (546, 315, 'Ibis, sacred');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (473, 706, 'Great horned owl');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (26, 411, 'Pintail, bahama');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (86, 287, 'Marine iguana');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (755, 204, 'Gnu, brindled');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (600, 26, 'Palm squirrel');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (668, 987, 'Brown capuchin');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (9, 63, 'Phalarope, red');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (439, 660, 'Paddy heron (unidentified)');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (442, 780, 'Hawk, galapagos');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (315, 249, 'Bush dog');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (754, 431, 'Sifaka, verreaux''s');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (798, 544, 'Admiral, indian red');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (480, 399, 'Swamp deer');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (213, 857, 'Rattlesnake, horned');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (37, 671, 'Goose, egyptian');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (542, 386, 'Sable antelope');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (952, 641, 'Gulls (unidentified)');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (920, 843, 'Boat-billed heron');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (628, 472, 'Greater roadrunner');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (617, 162, 'Snowy egret');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (18, 167, 'Lizard, frilled');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (150, 360, 'Fat-tailed dunnart');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (804, 144, 'Macaw, red and blue');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (506, 991, 'Cape white-eye');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (143, 273, 'Guanaco');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (463, 761, 'Bateleur eagle');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (255, 83, 'Armadillo, seven-banded');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (819, 296, 'Jungle cat');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (483, 390, 'Roller, lilac-breasted');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (829, 772, 'Genet, small-spotted');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (55, 979, 'Waxbill, violet-eared');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (489, 285, 'House sparrow');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (837, 216, 'Lynx, african');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (335, 466, 'Grey heron');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (734, 322, 'Gazer, sun');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (462, 504, 'Francolin, coqui');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (895, 994, 'Red-capped cardinal');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (756, 705, 'Rufous-collared sparrow');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (7, 257, 'Gecko, barking');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (459, 761, 'Yellow-headed caracara');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (468, 538, 'Grison');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (900, 42, 'Black-winged stilt');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (407, 6, 'Tortoise, burmese black mountain');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (428, 356, 'White-nosed coatimundi');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (5, 82, 'Red-capped cardinal');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (349, 862, 'Heron, gray');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (567, 771, 'Buffalo, asian water');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (968, 191, 'Siskin, yellow-rumped');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (112, 801, 'African wild dog');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (952, 361, 'Dragon, asian water');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (646, 201, 'Great egret');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (411, 911, 'Gecko, bent-toed');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (956, 568, 'Potoroo');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (601, 308, 'Beaver, north american');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (825, 983, 'Chacma baboon');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (630, 510, 'Loris, slender');
insert into trayecto (ID_ESTACION, ID_TREN, nombre) values (168, 280, 'Southern ground hornbill');
