insert into tren (modelo, capacidad) values ('Range Rover', 1);
insert into tren (modelo, capacidad) values ('SC', 2);
insert into tren (modelo, capacidad) values ('F250', 3);
insert into tren (modelo, capacidad) values ('E-Series', 4);
insert into tren (modelo, capacidad) values ('Ram Van 3500', 5);
insert into tren (modelo, capacidad) values ('Q5', 6);
insert into tren (modelo, capacidad) values ('Eos', 7);
insert into tren (modelo, capacidad) values ('G-Class', 8);
insert into tren (modelo, capacidad) values ('Ram Van B250', 9);
insert into tren (modelo, capacidad) values ('Aspire', 10);
insert into tren (modelo, capacidad) values ('Verona', 11);
insert into tren (modelo, capacidad) values ('S80', 12);
insert into tren (modelo, capacidad) values ('Tahoe', 13);
insert into tren (modelo, capacidad) values ('Aspen', 14);
insert into tren (modelo, capacidad) values ('Justy', 15);
insert into tren (modelo, capacidad) values ('RAV4', 16);
insert into tren (modelo, capacidad) values ('S2000', 17);
insert into tren (modelo, capacidad) values ('Impreza', 18);
insert into tren (modelo, capacidad) values ('G-Class', 19);
insert into tren (modelo, capacidad) values ('MX-5', 20);
insert into tren (modelo, capacidad) values ('Integra', 21);
insert into tren (modelo, capacidad) values ('Focus', 22);
insert into tren (modelo, capacidad) values ('5 Series', 23);
insert into tren (modelo, capacidad) values ('Corolla', 24);
insert into tren (modelo, capacidad) values ('SVX', 25);
insert into tren (modelo, capacidad) values ('Grand Vitara', 26);
insert into tren (modelo, capacidad) values ('90', 27);
insert into tren (modelo, capacidad) values ('Galant', 28);
insert into tren (modelo, capacidad) values ('Silverado', 29);
insert into tren (modelo, capacidad) values ('Accent', 30);
insert into tren (modelo, capacidad) values ('Camaro', 31);
insert into tren (modelo, capacidad) values ('Murciélago', 32);
insert into tren (modelo, capacidad) values ('Savana 2500', 33);
insert into tren (modelo, capacidad) values ('Fox', 34);
insert into tren (modelo, capacidad) values ('Grand Prix', 35);
insert into tren (modelo, capacidad) values ('Golf', 36);
insert into tren (modelo, capacidad) values ('Forester', 37);
insert into tren (modelo, capacidad) values ('FX', 38);
insert into tren (modelo, capacidad) values ('Maxima', 39);
insert into tren (modelo, capacidad) values ('New Beetle', 40);
insert into tren (modelo, capacidad) values ('Paseo', 41);
insert into tren (modelo, capacidad) values ('H1', 42);
insert into tren (modelo, capacidad) values ('Ipsum', 43);
insert into tren (modelo, capacidad) values ('Solstice', 44);
insert into tren (modelo, capacidad) values ('Navajo', 45);
insert into tren (modelo, capacidad) values ('Probe', 46);
insert into tren (modelo, capacidad) values ('HS', 47);
insert into tren (modelo, capacidad) values ('Camaro', 48);
insert into tren (modelo, capacidad) values ('X3', 49);
insert into tren (modelo, capacidad) values ('DTS', 50);
insert into tren (modelo, capacidad) values ('M5', 51);
insert into tren (modelo, capacidad) values ('Camry Hybrid', 52);
insert into tren (modelo, capacidad) values ('Astro', 53);
insert into tren (modelo, capacidad) values ('C-MAX Hybrid', 54);
insert into tren (modelo, capacidad) values ('Countach', 55);
insert into tren (modelo, capacidad) values ('Murciélago', 56);
insert into tren (modelo, capacidad) values ('Sorento', 57);
insert into tren (modelo, capacidad) values ('Storm', 58);
insert into tren (modelo, capacidad) values ('Sentra', 59);
insert into tren (modelo, capacidad) values ('Sienna', 60);
insert into tren (modelo, capacidad) values ('Vibe', 61);
insert into tren (modelo, capacidad) values ('RX Hybrid', 62);
insert into tren (modelo, capacidad) values ('Caliber', 63);
insert into tren (modelo, capacidad) values ('Lynx', 64);
insert into tren (modelo, capacidad) values ('Suburban 1500', 65);
insert into tren (modelo, capacidad) values ('Enclave', 66);
insert into tren (modelo, capacidad) values ('Daewoo Lacetti', 67);
insert into tren (modelo, capacidad) values ('Avalanche', 68);
insert into tren (modelo, capacidad) values ('Sonata', 69);
insert into tren (modelo, capacidad) values ('PT Cruiser', 70);
insert into tren (modelo, capacidad) values ('Yukon XL 1500', 71);
insert into tren (modelo, capacidad) values ('Bonneville', 72);
insert into tren (modelo, capacidad) values ('V8 Vantage', 73);
insert into tren (modelo, capacidad) values ('Safari', 74);
insert into tren (modelo, capacidad) values ('Cobalt', 75);
insert into tren (modelo, capacidad) values ('S5', 76);
insert into tren (modelo, capacidad) values ('9-7X', 77);
insert into tren (modelo, capacidad) values ('A4', 78);
insert into tren (modelo, capacidad) values ('Electra', 79);
insert into tren (modelo, capacidad) values ('Altima', 80);
insert into tren (modelo, capacidad) values ('Bonneville', 81);
insert into tren (modelo, capacidad) values ('Miata MX-5', 82);
insert into tren (modelo, capacidad) values ('Passat', 83);
insert into tren (modelo, capacidad) values ('Galant', 84);
insert into tren (modelo, capacidad) values ('911', 85);
insert into tren (modelo, capacidad) values ('Touareg', 86);
insert into tren (modelo, capacidad) values ('Q', 87);
insert into tren (modelo, capacidad) values ('TrailBlazer', 88);
insert into tren (modelo, capacidad) values ('Altima', 89);
insert into tren (modelo, capacidad) values ('V70', 90);
insert into tren (modelo, capacidad) values ('Accent', 91);
insert into tren (modelo, capacidad) values ('200', 92);
insert into tren (modelo, capacidad) values ('Silverado 2500', 93);
insert into tren (modelo, capacidad) values ('7 Series', 94);
insert into tren (modelo, capacidad) values ('SRX', 95);
insert into tren (modelo, capacidad) values ('Sebring', 96);
insert into tren (modelo, capacidad) values ('Ram Van 1500', 97);
insert into tren (modelo, capacidad) values ('Mustang', 98);
insert into tren (modelo, capacidad) values ('DeVille', 99);
insert into tren (modelo, capacidad) values ('Eclipse', 100);
insert into tren (modelo, capacidad) values ('88', 101);
insert into tren (modelo, capacidad) values ('88', 102);
insert into tren (modelo, capacidad) values ('Diablo', 103);
insert into tren (modelo, capacidad) values ('LS', 104);
insert into tren (modelo, capacidad) values ('A8', 105);
insert into tren (modelo, capacidad) values ('RVR', 106);
insert into tren (modelo, capacidad) values ('Karif', 107);
insert into tren (modelo, capacidad) values ('Silhouette', 108);
insert into tren (modelo, capacidad) values ('Town & Country', 109);
insert into tren (modelo, capacidad) values ('626', 110);
insert into tren (modelo, capacidad) values ('NSX', 111);
insert into tren (modelo, capacidad) values ('Beretta', 112);
insert into tren (modelo, capacidad) values ('Focus', 113);
insert into tren (modelo, capacidad) values ('Corrado', 114);
insert into tren (modelo, capacidad) values ('Millenia', 115);
insert into tren (modelo, capacidad) values ('XC70', 116);
insert into tren (modelo, capacidad) values ('Corvette', 117);
insert into tren (modelo, capacidad) values ('Century', 118);
insert into tren (modelo, capacidad) values ('Suburban 1500', 119);
insert into tren (modelo, capacidad) values ('Savana 1500', 120);
insert into tren (modelo, capacidad) values ('MKT', 121);
insert into tren (modelo, capacidad) values ('Discovery', 122);
insert into tren (modelo, capacidad) values ('Legacy', 123);
insert into tren (modelo, capacidad) values ('F-Series', 124);
insert into tren (modelo, capacidad) values ('Malibu', 125);
insert into tren (modelo, capacidad) values ('Mountaineer', 126);
insert into tren (modelo, capacidad) values ('Viper RT/10', 127);
insert into tren (modelo, capacidad) values ('Mazda3', 128);
insert into tren (modelo, capacidad) values ('C30', 129);
insert into tren (modelo, capacidad) values ('Stanza', 130);
insert into tren (modelo, capacidad) values ('Bonneville', 131);
insert into tren (modelo, capacidad) values ('Phaeton', 132);
insert into tren (modelo, capacidad) values ('T100 Xtra', 133);
insert into tren (modelo, capacidad) values ('Explorer', 134);
insert into tren (modelo, capacidad) values ('2500 Club Coupe', 135);
insert into tren (modelo, capacidad) values ('QX56', 136);
insert into tren (modelo, capacidad) values ('Freestar', 137);
insert into tren (modelo, capacidad) values ('V90', 138);
insert into tren (modelo, capacidad) values ('Escort', 139);
insert into tren (modelo, capacidad) values ('Cooper', 140);
insert into tren (modelo, capacidad) values ('Accent', 141);
insert into tren (modelo, capacidad) values ('Xterra', 142);
insert into tren (modelo, capacidad) values ('Stratus', 143);
insert into tren (modelo, capacidad) values ('164', 144);
insert into tren (modelo, capacidad) values ('Safari', 145);
insert into tren (modelo, capacidad) values ('Express 2500', 146);
insert into tren (modelo, capacidad) values ('Vibe', 147);
insert into tren (modelo, capacidad) values ('Cavalier', 148);
insert into tren (modelo, capacidad) values ('H1', 149);
insert into tren (modelo, capacidad) values ('QX56', 150);
insert into tren (modelo, capacidad) values ('3500', 151);
insert into tren (modelo, capacidad) values ('RX', 152);
insert into tren (modelo, capacidad) values ('Blazer', 153);
insert into tren (modelo, capacidad) values ('SLS-Class', 154);
insert into tren (modelo, capacidad) values ('Ram', 155);
insert into tren (modelo, capacidad) values ('rio', 156);
insert into tren (modelo, capacidad) values ('300M', 157);
insert into tren (modelo, capacidad) values ('Sierra 1500', 158);
insert into tren (modelo, capacidad) values ('G-Series 2500', 159);
insert into tren (modelo, capacidad) values ('Avalanche 2500', 160);
insert into tren (modelo, capacidad) values ('SC', 161);
insert into tren (modelo, capacidad) values ('Cooper', 162);
insert into tren (modelo, capacidad) values ('Rio', 163);
insert into tren (modelo, capacidad) values ('Escape', 164);
insert into tren (modelo, capacidad) values ('EXP', 165);
insert into tren (modelo, capacidad) values ('62', 166);
insert into tren (modelo, capacidad) values ('Trooper', 167);
insert into tren (modelo, capacidad) values ('MKS', 168);
insert into tren (modelo, capacidad) values ('S6', 169);
insert into tren (modelo, capacidad) values ('Concorde', 170);
insert into tren (modelo, capacidad) values ('Grand Caravan', 171);
insert into tren (modelo, capacidad) values ('E-Class', 172);
insert into tren (modelo, capacidad) values ('Malibu', 173);
insert into tren (modelo, capacidad) values ('Crown Victoria', 174);
insert into tren (modelo, capacidad) values ('Impala', 175);
insert into tren (modelo, capacidad) values ('Explorer', 176);
insert into tren (modelo, capacidad) values ('Rodeo', 177);
insert into tren (modelo, capacidad) values ('Carens', 178);
insert into tren (modelo, capacidad) values ('2500', 179);
insert into tren (modelo, capacidad) values ('Stealth', 180);
insert into tren (modelo, capacidad) values ('Colorado', 181);
insert into tren (modelo, capacidad) values ('Amanti', 182);
insert into tren (modelo, capacidad) values ('Sportage', 183);
insert into tren (modelo, capacidad) values ('911', 184);
insert into tren (modelo, capacidad) values ('LeMans', 185);
insert into tren (modelo, capacidad) values ('Equator', 186);
insert into tren (modelo, capacidad) values ('Astro', 187);
insert into tren (modelo, capacidad) values ('Bravada', 188);
insert into tren (modelo, capacidad) values ('E-Series', 189);
insert into tren (modelo, capacidad) values ('S6', 190);
insert into tren (modelo, capacidad) values ('Pathfinder', 191);
insert into tren (modelo, capacidad) values ('Sidekick', 192);
insert into tren (modelo, capacidad) values ('Chariot', 193);
insert into tren (modelo, capacidad) values ('Sonoma Club Coupe', 194);
insert into tren (modelo, capacidad) values ('Accord', 195);
insert into tren (modelo, capacidad) values ('Samurai', 196);
insert into tren (modelo, capacidad) values ('Boxster', 197);
insert into tren (modelo, capacidad) values ('Golf', 198);
insert into tren (modelo, capacidad) values ('Landaulet', 199);
insert into tren (modelo, capacidad) values ('Pajero', 200);
insert into tren (modelo, capacidad) values ('Jimmy', 201);
insert into tren (modelo, capacidad) values ('3500', 202);
insert into tren (modelo, capacidad) values ('Cayenne', 203);
insert into tren (modelo, capacidad) values ('3 Series', 204);
insert into tren (modelo, capacidad) values ('Tredia', 205);
insert into tren (modelo, capacidad) values ('Galant', 206);
insert into tren (modelo, capacidad) values ('525', 207);
insert into tren (modelo, capacidad) values ('Vision', 208);
insert into tren (modelo, capacidad) values ('G', 209);
insert into tren (modelo, capacidad) values ('7 Series', 210);
insert into tren (modelo, capacidad) values ('MPV', 211);
insert into tren (modelo, capacidad) values ('Econoline E150', 212);
insert into tren (modelo, capacidad) values ('Blazer', 213);
insert into tren (modelo, capacidad) values ('Equator', 214);
insert into tren (modelo, capacidad) values ('TL', 215);
insert into tren (modelo, capacidad) values ('Diablo', 216);
insert into tren (modelo, capacidad) values ('1500', 217);
insert into tren (modelo, capacidad) values ('Firebird', 218);
insert into tren (modelo, capacidad) values ('Aerostar', 219);
insert into tren (modelo, capacidad) values ('Explorer Sport Trac', 220);
insert into tren (modelo, capacidad) values ('Savana 2500', 221);
insert into tren (modelo, capacidad) values ('Ram 2500', 222);
insert into tren (modelo, capacidad) values ('Pacifica', 223);
insert into tren (modelo, capacidad) values ('Metro', 224);
insert into tren (modelo, capacidad) values ('Avanti', 225);
insert into tren (modelo, capacidad) values ('LX', 226);
insert into tren (modelo, capacidad) values ('530', 227);
insert into tren (modelo, capacidad) values ('Hombre Space', 228);
insert into tren (modelo, capacidad) values ('Passat', 229);
insert into tren (modelo, capacidad) values ('Prius', 230);
insert into tren (modelo, capacidad) values ('Explorer', 231);
insert into tren (modelo, capacidad) values ('Lynx', 232);
insert into tren (modelo, capacidad) values ('SL-Class', 233);
insert into tren (modelo, capacidad) values ('V8', 234);
insert into tren (modelo, capacidad) values ('Titan', 235);
insert into tren (modelo, capacidad) values ('Probe', 236);
insert into tren (modelo, capacidad) values ('Solara', 237);
insert into tren (modelo, capacidad) values ('G-Class', 238);
insert into tren (modelo, capacidad) values ('Outback Sport', 239);
insert into tren (modelo, capacidad) values ('Freestar', 240);
insert into tren (modelo, capacidad) values ('SM', 241);
insert into tren (modelo, capacidad) values ('300SL', 242);
insert into tren (modelo, capacidad) values ('9-5', 243);
insert into tren (modelo, capacidad) values ('Firefly', 244);
insert into tren (modelo, capacidad) values ('SLK-Class', 245);
insert into tren (modelo, capacidad) values ('Charger', 246);
insert into tren (modelo, capacidad) values ('Town Car', 247);
insert into tren (modelo, capacidad) values ('V50', 248);
insert into tren (modelo, capacidad) values ('Trans Sport', 249);
insert into tren (modelo, capacidad) values ('GT500', 250);
insert into tren (modelo, capacidad) values ('900', 251);
insert into tren (modelo, capacidad) values ('NSX', 252);
insert into tren (modelo, capacidad) values ('Escalade EXT', 253);
insert into tren (modelo, capacidad) values ('CTS', 254);
insert into tren (modelo, capacidad) values ('S-Series', 255);
insert into tren (modelo, capacidad) values ('Freelander', 256);
insert into tren (modelo, capacidad) values ('Firebird', 257);
insert into tren (modelo, capacidad) values ('Defender', 258);
insert into tren (modelo, capacidad) values ('Suburban', 259);
insert into tren (modelo, capacidad) values ('S-Series', 260);
insert into tren (modelo, capacidad) values ('Sportage', 261);
insert into tren (modelo, capacidad) values ('A6', 262);
insert into tren (modelo, capacidad) values ('Camry Solara', 263);
insert into tren (modelo, capacidad) values ('Grand Am', 264);
insert into tren (modelo, capacidad) values ('Outlook', 265);
insert into tren (modelo, capacidad) values ('Cougar', 266);
insert into tren (modelo, capacidad) values ('Grand Caravan', 267);
insert into tren (modelo, capacidad) values ('Charger', 268);
insert into tren (modelo, capacidad) values ('Odyssey', 269);
insert into tren (modelo, capacidad) values ('Civic', 270);
insert into tren (modelo, capacidad) values ('Topaz', 271);
insert into tren (modelo, capacidad) values ('Ram 50', 272);
insert into tren (modelo, capacidad) values ('CL', 273);
insert into tren (modelo, capacidad) values ('Silhouette', 274);
insert into tren (modelo, capacidad) values ('S40', 275);
insert into tren (modelo, capacidad) values ('TT', 276);
insert into tren (modelo, capacidad) values ('Daewoo Kalos', 277);
insert into tren (modelo, capacidad) values ('968', 278);
insert into tren (modelo, capacidad) values ('Lumina', 279);
insert into tren (modelo, capacidad) values ('F-Series Super Duty', 280);
insert into tren (modelo, capacidad) values ('Galant', 281);
insert into tren (modelo, capacidad) values ('IS', 282);
insert into tren (modelo, capacidad) values ('LS', 283);
insert into tren (modelo, capacidad) values ('Cutlass Supreme', 284);
insert into tren (modelo, capacidad) values ('E250', 285);
insert into tren (modelo, capacidad) values ('Eclipse', 286);
insert into tren (modelo, capacidad) values ('H1', 287);
insert into tren (modelo, capacidad) values ('Range Rover', 288);
insert into tren (modelo, capacidad) values ('Metro', 289);
insert into tren (modelo, capacidad) values ('tC', 290);
insert into tren (modelo, capacidad) values ('A8', 291);
insert into tren (modelo, capacidad) values ('Stratus', 292);
insert into tren (modelo, capacidad) values ('Sable', 293);
insert into tren (modelo, capacidad) values ('Legacy', 294);
insert into tren (modelo, capacidad) values ('Breeze', 295);
insert into tren (modelo, capacidad) values ('3500', 296);
insert into tren (modelo, capacidad) values ('Cougar', 297);
insert into tren (modelo, capacidad) values ('Corvette', 298);
insert into tren (modelo, capacidad) values ('E350', 299);
insert into tren (modelo, capacidad) values ('Swift', 300);
insert into tren (modelo, capacidad) values ('S-Type', 301);
insert into tren (modelo, capacidad) values ('Passat', 302);
insert into tren (modelo, capacidad) values ('100', 303);
insert into tren (modelo, capacidad) values ('QX', 304);
insert into tren (modelo, capacidad) values ('Dakota Club', 305);
insert into tren (modelo, capacidad) values ('Traverse', 306);
insert into tren (modelo, capacidad) values ('LeMans', 307);
insert into tren (modelo, capacidad) values ('Lumina', 308);
insert into tren (modelo, capacidad) values ('8 Series', 309);
insert into tren (modelo, capacidad) values ('Century', 310);
insert into tren (modelo, capacidad) values ('Tracer', 311);
insert into tren (modelo, capacidad) values ('Sebring', 312);
insert into tren (modelo, capacidad) values ('XL-7', 313);
insert into tren (modelo, capacidad) values ('F-Series', 314);
insert into tren (modelo, capacidad) values ('Legacy', 315);
insert into tren (modelo, capacidad) values ('Solstice', 316);
insert into tren (modelo, capacidad) values ('Odyssey', 317);
insert into tren (modelo, capacidad) values ('QX56', 318);
insert into tren (modelo, capacidad) values ('S80', 319);
insert into tren (modelo, capacidad) values ('Ram', 320);
insert into tren (modelo, capacidad) values ('Freelander', 321);
insert into tren (modelo, capacidad) values ('Charger', 322);
insert into tren (modelo, capacidad) values ('MPV', 323);
insert into tren (modelo, capacidad) values ('Nitro', 324);
insert into tren (modelo, capacidad) values ('Town Car', 325);
insert into tren (modelo, capacidad) values ('Tempest', 326);
insert into tren (modelo, capacidad) values ('RAV4', 327);
insert into tren (modelo, capacidad) values ('Dakota', 328);
insert into tren (modelo, capacidad) values ('Firebird', 329);
insert into tren (modelo, capacidad) values ('G', 330);
insert into tren (modelo, capacidad) values ('911', 331);
insert into tren (modelo, capacidad) values ('M', 332);
insert into tren (modelo, capacidad) values ('Camry', 333);
insert into tren (modelo, capacidad) values ('Mazda6', 334);
insert into tren (modelo, capacidad) values ('Cruze', 335);
insert into tren (modelo, capacidad) values ('Nuova 500', 336);
insert into tren (modelo, capacidad) values ('Civic', 337);
insert into tren (modelo, capacidad) values ('Probe', 338);
insert into tren (modelo, capacidad) values ('Allroad', 339);
insert into tren (modelo, capacidad) values ('G25', 340);
insert into tren (modelo, capacidad) values ('Five Hundred', 341);
insert into tren (modelo, capacidad) values ('Dakota', 342);
insert into tren (modelo, capacidad) values ('Expedition', 343);
insert into tren (modelo, capacidad) values ('Yukon XL 2500', 344);
insert into tren (modelo, capacidad) values ('Viper', 345);
insert into tren (modelo, capacidad) values ('Firefly', 346);
insert into tren (modelo, capacidad) values ('600', 347);
insert into tren (modelo, capacidad) values ('Express 1500', 348);
insert into tren (modelo, capacidad) values ('RL', 349);
insert into tren (modelo, capacidad) values ('Grand Voyager', 350);
insert into tren (modelo, capacidad) values ('SRX', 351);
insert into tren (modelo, capacidad) values ('V50', 352);
insert into tren (modelo, capacidad) values ('Fiesta', 353);
insert into tren (modelo, capacidad) values ('Corvette', 354);
insert into tren (modelo, capacidad) values ('Prius v', 355);
insert into tren (modelo, capacidad) values ('Enclave', 356);
insert into tren (modelo, capacidad) values ('Viper RT/10', 357);
insert into tren (modelo, capacidad) values ('Galant', 358);
insert into tren (modelo, capacidad) values ('Canyon', 359);
insert into tren (modelo, capacidad) values ('900', 360);
insert into tren (modelo, capacidad) values ('Corolla', 361);
insert into tren (modelo, capacidad) values ('Sentra', 362);
insert into tren (modelo, capacidad) values ('Kizashi', 363);
insert into tren (modelo, capacidad) values ('Tacoma Xtra', 364);
insert into tren (modelo, capacidad) values ('Grand Marquis', 365);
insert into tren (modelo, capacidad) values ('Thunderbird', 366);
insert into tren (modelo, capacidad) values ('Compass', 367);
insert into tren (modelo, capacidad) values ('Horizon', 368);
insert into tren (modelo, capacidad) values ('F-Series', 369);
insert into tren (modelo, capacidad) values ('Ram 3500', 370);
insert into tren (modelo, capacidad) values ('A8', 371);
insert into tren (modelo, capacidad) values ('300', 372);
insert into tren (modelo, capacidad) values ('S-Type', 373);
insert into tren (modelo, capacidad) values ('500E', 374);
insert into tren (modelo, capacidad) values ('Corvette', 375);
insert into tren (modelo, capacidad) values ('Sable', 376);
insert into tren (modelo, capacidad) values ('Grand Voyager', 377);
insert into tren (modelo, capacidad) values ('Grand Am', 378);
insert into tren (modelo, capacidad) values ('Monte Carlo', 379);
insert into tren (modelo, capacidad) values ('Leone', 380);
insert into tren (modelo, capacidad) values ('Corolla', 381);
insert into tren (modelo, capacidad) values ('Town Car', 382);
insert into tren (modelo, capacidad) values ('XC90', 383);
insert into tren (modelo, capacidad) values ('Capri', 384);
insert into tren (modelo, capacidad) values ('Freestyle', 385);
insert into tren (modelo, capacidad) values ('Maxima', 386);
insert into tren (modelo, capacidad) values ('V70', 387);
insert into tren (modelo, capacidad) values ('Genesis Coupe', 388);
insert into tren (modelo, capacidad) values ('Mustang', 389);
insert into tren (modelo, capacidad) values ('Diamante', 390);
insert into tren (modelo, capacidad) values ('E150', 391);
insert into tren (modelo, capacidad) values ('Sonoma Club', 392);
insert into tren (modelo, capacidad) values ('80', 393);
insert into tren (modelo, capacidad) values ('Pacifica', 394);
insert into tren (modelo, capacidad) values ('xA', 395);
insert into tren (modelo, capacidad) values ('S10', 396);
insert into tren (modelo, capacidad) values ('MPV', 397);
insert into tren (modelo, capacidad) values ('xD', 398);
insert into tren (modelo, capacidad) values ('Vibe', 399);
insert into tren (modelo, capacidad) values ('LeSabre', 400);
insert into tren (modelo, capacidad) values ('Sierra 1500', 401);
insert into tren (modelo, capacidad) values ('Explorer', 402);
insert into tren (modelo, capacidad) values ('xA', 403);
insert into tren (modelo, capacidad) values ('Galaxie', 404);
insert into tren (modelo, capacidad) values ('900', 405);
insert into tren (modelo, capacidad) values ('MPV', 406);
insert into tren (modelo, capacidad) values ('Milan', 407);
insert into tren (modelo, capacidad) values ('X3', 408);
insert into tren (modelo, capacidad) values ('V70', 409);
insert into tren (modelo, capacidad) values ('Camry Solara', 410);
insert into tren (modelo, capacidad) values ('E350', 411);
insert into tren (modelo, capacidad) values ('Achieva', 412);
insert into tren (modelo, capacidad) values ('Sentra', 413);
insert into tren (modelo, capacidad) values ('Accord', 414);
insert into tren (modelo, capacidad) values ('X6', 415);
insert into tren (modelo, capacidad) values ('Escalade', 416);
insert into tren (modelo, capacidad) values ('Swift', 417);
insert into tren (modelo, capacidad) values ('530', 418);
insert into tren (modelo, capacidad) values ('Explorer Sport Trac', 419);
insert into tren (modelo, capacidad) values ('944', 420);
insert into tren (modelo, capacidad) values ('Town Car', 421);
insert into tren (modelo, capacidad) values ('Landaulet', 422);
insert into tren (modelo, capacidad) values ('57', 423);
insert into tren (modelo, capacidad) values ('GLK-Class', 424);
insert into tren (modelo, capacidad) values ('XJ Series', 425);
insert into tren (modelo, capacidad) values ('A3', 426);
insert into tren (modelo, capacidad) values ('S4', 427);
insert into tren (modelo, capacidad) values ('A4', 428);
insert into tren (modelo, capacidad) values ('Neon', 429);
insert into tren (modelo, capacidad) values ('Countryman', 430);
insert into tren (modelo, capacidad) values ('Loyale', 431);
insert into tren (modelo, capacidad) values ('Pathfinder', 432);
insert into tren (modelo, capacidad) values ('B9 Tribeca', 433);
insert into tren (modelo, capacidad) values ('Tundra', 434);
insert into tren (modelo, capacidad) values ('Tracer', 435);
insert into tren (modelo, capacidad) values ('Elantra', 436);
insert into tren (modelo, capacidad) values ('NSX', 437);
insert into tren (modelo, capacidad) values ('Dynasty', 438);
insert into tren (modelo, capacidad) values ('Protege', 439);
insert into tren (modelo, capacidad) values ('Diamante', 440);
insert into tren (modelo, capacidad) values ('Phantom', 441);
insert into tren (modelo, capacidad) values ('911', 442);
insert into tren (modelo, capacidad) values ('Seville', 443);
insert into tren (modelo, capacidad) values ('7 Series', 444);
insert into tren (modelo, capacidad) values ('Continental', 445);
insert into tren (modelo, capacidad) values ('LR2', 446);
insert into tren (modelo, capacidad) values ('Corvette', 447);
insert into tren (modelo, capacidad) values ('H1', 448);
insert into tren (modelo, capacidad) values ('Dakota Club', 449);
insert into tren (modelo, capacidad) values ('GTO', 450);
insert into tren (modelo, capacidad) values ('7 Series', 451);
insert into tren (modelo, capacidad) values ('NSX', 452);
insert into tren (modelo, capacidad) values ('Quest', 453);
insert into tren (modelo, capacidad) values ('F-Series', 454);
insert into tren (modelo, capacidad) values ('Savana 1500', 455);
insert into tren (modelo, capacidad) values ('Regal', 456);
insert into tren (modelo, capacidad) values ('Town & Country', 457);
insert into tren (modelo, capacidad) values ('Avalanche 2500', 458);
insert into tren (modelo, capacidad) values ('Firebird', 459);
insert into tren (modelo, capacidad) values ('Nubira', 460);
insert into tren (modelo, capacidad) values ('Viper RT/10', 461);
insert into tren (modelo, capacidad) values ('525', 462);
insert into tren (modelo, capacidad) values ('Malibu', 463);
insert into tren (modelo, capacidad) values ('Town Car', 464);
insert into tren (modelo, capacidad) values ('S5', 465);
insert into tren (modelo, capacidad) values ('V70', 466);
insert into tren (modelo, capacidad) values ('Electra', 467);
insert into tren (modelo, capacidad) values ('Fiero', 468);
insert into tren (modelo, capacidad) values ('Sportvan G30', 469);
insert into tren (modelo, capacidad) values ('Continental', 470);
insert into tren (modelo, capacidad) values ('Suburban 1500', 471);
insert into tren (modelo, capacidad) values ('3500 Club Coupe', 472);
insert into tren (modelo, capacidad) values ('Accent', 473);
insert into tren (modelo, capacidad) values ('Exige', 474);
insert into tren (modelo, capacidad) values ('9-3', 475);
insert into tren (modelo, capacidad) values ('Familia', 476);
insert into tren (modelo, capacidad) values ('Vibe', 477);
insert into tren (modelo, capacidad) values ('Protege', 478);
insert into tren (modelo, capacidad) values ('Grand Am', 479);
insert into tren (modelo, capacidad) values ('XL-7', 480);
insert into tren (modelo, capacidad) values ('3500', 481);
insert into tren (modelo, capacidad) values ('Tempo', 482);
insert into tren (modelo, capacidad) values ('Space', 483);
insert into tren (modelo, capacidad) values ('Tahoe', 484);
insert into tren (modelo, capacidad) values ('Firebird', 485);
insert into tren (modelo, capacidad) values ('CT', 486);
insert into tren (modelo, capacidad) values ('5000S', 487);
insert into tren (modelo, capacidad) values ('E-Class', 488);
insert into tren (modelo, capacidad) values ('DeVille', 489);
insert into tren (modelo, capacidad) values ('XL7', 490);
insert into tren (modelo, capacidad) values ('Accord', 491);
insert into tren (modelo, capacidad) values ('Grand Marquis', 492);
insert into tren (modelo, capacidad) values ('Esprit', 493);
insert into tren (modelo, capacidad) values ('Trans Sport', 494);
insert into tren (modelo, capacidad) values ('Tiburon', 495);
insert into tren (modelo, capacidad) values ('Model T', 496);
insert into tren (modelo, capacidad) values ('S70', 497);
insert into tren (modelo, capacidad) values ('Cirrus', 498);
insert into tren (modelo, capacidad) values ('Aveo', 499);
insert into tren (modelo, capacidad) values ('NSX', 500);
insert into tren (modelo, capacidad) values ('Prelude', 501);
insert into tren (modelo, capacidad) values ('Sable', 502);
insert into tren (modelo, capacidad) values ('Quattroporte', 503);
insert into tren (modelo, capacidad) values ('Explorer', 504);
insert into tren (modelo, capacidad) values ('Insight', 505);
insert into tren (modelo, capacidad) values ('Mazda3', 506);
insert into tren (modelo, capacidad) values ('911', 507);
insert into tren (modelo, capacidad) values ('Xterra', 508);
insert into tren (modelo, capacidad) values ('H3', 509);
insert into tren (modelo, capacidad) values ('Alero', 510);
insert into tren (modelo, capacidad) values ('Escort', 511);
insert into tren (modelo, capacidad) values ('Escalade ESV', 512);
insert into tren (modelo, capacidad) values ('XC70', 513);
insert into tren (modelo, capacidad) values ('Solstice', 514);
insert into tren (modelo, capacidad) values ('740', 515);
insert into tren (modelo, capacidad) values ('Rally Wagon G2500', 516);
insert into tren (modelo, capacidad) values ('Grand Marquis', 517);
insert into tren (modelo, capacidad) values ('Quest', 518);
insert into tren (modelo, capacidad) values ('Escalade EXT', 519);
insert into tren (modelo, capacidad) values ('S90', 520);
insert into tren (modelo, capacidad) values ('Chariot', 521);
insert into tren (modelo, capacidad) values ('Swift', 522);
insert into tren (modelo, capacidad) values ('Reno', 523);
insert into tren (modelo, capacidad) values ('Crown Victoria', 524);
insert into tren (modelo, capacidad) values ('Civic', 525);
insert into tren (modelo, capacidad) values ('Interceptor', 526);
insert into tren (modelo, capacidad) values ('DeVille', 527);
insert into tren (modelo, capacidad) values ('S-Type', 528);
insert into tren (modelo, capacidad) values ('Outback', 529);
insert into tren (modelo, capacidad) values ('QX', 530);
insert into tren (modelo, capacidad) values ('626', 531);
insert into tren (modelo, capacidad) values ('Passat', 532);
insert into tren (modelo, capacidad) values ('9-5', 533);
insert into tren (modelo, capacidad) values ('62', 534);
insert into tren (modelo, capacidad) values ('RL', 535);
insert into tren (modelo, capacidad) values ('Justy', 536);
insert into tren (modelo, capacidad) values ('C8 Spyder', 537);
insert into tren (modelo, capacidad) values ('F350', 538);
insert into tren (modelo, capacidad) values ('Cougar', 539);
insert into tren (modelo, capacidad) values ('Omni', 540);
insert into tren (modelo, capacidad) values ('3000GT', 541);
insert into tren (modelo, capacidad) values ('Sienna', 542);
insert into tren (modelo, capacidad) values ('Exige', 543);
insert into tren (modelo, capacidad) values ('7 Series', 544);
insert into tren (modelo, capacidad) values ('Mazda6', 545);
insert into tren (modelo, capacidad) values ('GTI', 546);
insert into tren (modelo, capacidad) values ('S8', 547);
insert into tren (modelo, capacidad) values ('LS', 548);
insert into tren (modelo, capacidad) values ('E-Series', 549);
insert into tren (modelo, capacidad) values ('Grand Am', 550);
insert into tren (modelo, capacidad) values ('Excel', 551);
insert into tren (modelo, capacidad) values ('Yukon XL 2500', 552);
insert into tren (modelo, capacidad) values ('Eldorado', 553);
insert into tren (modelo, capacidad) values ('Sunfire', 554);
insert into tren (modelo, capacidad) values ('Savana 3500', 555);
insert into tren (modelo, capacidad) values ('Aerostar', 556);
insert into tren (modelo, capacidad) values ('Liberty', 557);
insert into tren (modelo, capacidad) values ('929', 558);
insert into tren (modelo, capacidad) values ('Range Rover', 559);
insert into tren (modelo, capacidad) values ('Altima', 560);
insert into tren (modelo, capacidad) values ('Continental GT', 561);
insert into tren (modelo, capacidad) values ('E250', 562);
insert into tren (modelo, capacidad) values ('B-Series', 563);
insert into tren (modelo, capacidad) values ('RX', 564);
insert into tren (modelo, capacidad) values ('Laser', 565);
insert into tren (modelo, capacidad) values ('Ram 2500', 566);
insert into tren (modelo, capacidad) values ('Seville', 567);
insert into tren (modelo, capacidad) values ('900', 568);
insert into tren (modelo, capacidad) values ('Golf III', 569);
insert into tren (modelo, capacidad) values ('Uplander', 570);
insert into tren (modelo, capacidad) values ('HHR', 571);
insert into tren (modelo, capacidad) values ('Town & Country', 572);
insert into tren (modelo, capacidad) values ('E-Class', 573);
insert into tren (modelo, capacidad) values ('Ram 3500', 574);
insert into tren (modelo, capacidad) values ('Rondo', 575);
insert into tren (modelo, capacidad) values ('Space', 576);
insert into tren (modelo, capacidad) values ('Ram 2500', 577);
insert into tren (modelo, capacidad) values ('Rio', 578);
insert into tren (modelo, capacidad) values ('Sierra 2500', 579);
insert into tren (modelo, capacidad) values ('T100', 580);
insert into tren (modelo, capacidad) values ('Intrepid', 581);
insert into tren (modelo, capacidad) values ('3 Series', 582);
insert into tren (modelo, capacidad) values ('Escort', 583);
insert into tren (modelo, capacidad) values ('XC90', 584);
insert into tren (modelo, capacidad) values ('300', 585);
insert into tren (modelo, capacidad) values ('4Runner', 586);
insert into tren (modelo, capacidad) values ('Silverado 2500', 587);
insert into tren (modelo, capacidad) values ('Pathfinder', 588);
insert into tren (modelo, capacidad) values ('LUV', 589);
insert into tren (modelo, capacidad) values ('MX-6', 590);
insert into tren (modelo, capacidad) values ('Passport', 591);
insert into tren (modelo, capacidad) values ('Fusion', 592);
insert into tren (modelo, capacidad) values ('Altima', 593);
insert into tren (modelo, capacidad) values ('Safari', 594);
insert into tren (modelo, capacidad) values ('NX', 595);
insert into tren (modelo, capacidad) values ('Sienna', 596);
insert into tren (modelo, capacidad) values ('B9 Tribeca', 597);
insert into tren (modelo, capacidad) values ('Tacoma', 598);
insert into tren (modelo, capacidad) values ('DB9', 599);
insert into tren (modelo, capacidad) values ('T100 Xtra', 600);
insert into tren (modelo, capacidad) values ('Ram 3500', 601);
insert into tren (modelo, capacidad) values ('MR2', 602);
insert into tren (modelo, capacidad) values ('LeMans', 603);
insert into tren (modelo, capacidad) values ('944', 604);
insert into tren (modelo, capacidad) values ('Grand Vitara', 605);
insert into tren (modelo, capacidad) values ('Cooper Clubman', 606);
insert into tren (modelo, capacidad) values ('Edge', 607);
insert into tren (modelo, capacidad) values ('Savana', 608);
insert into tren (modelo, capacidad) values ('Savana 3500', 609);
insert into tren (modelo, capacidad) values ('Coachbuilder', 610);
insert into tren (modelo, capacidad) values ('Probe', 611);
insert into tren (modelo, capacidad) values ('929', 612);
insert into tren (modelo, capacidad) values ('LS Hybrid', 613);
insert into tren (modelo, capacidad) values ('Grand Cherokee', 614);
insert into tren (modelo, capacidad) values ('Ram 1500', 615);
insert into tren (modelo, capacidad) values ('Civic', 616);
insert into tren (modelo, capacidad) values ('TundraMax', 617);
insert into tren (modelo, capacidad) values ('Azure', 618);
insert into tren (modelo, capacidad) values ('Lancer Evolution', 619);
insert into tren (modelo, capacidad) values ('Montana', 620);
insert into tren (modelo, capacidad) values ('Ram 1500', 621);
insert into tren (modelo, capacidad) values ('626', 622);
insert into tren (modelo, capacidad) values ('Cordia', 623);
insert into tren (modelo, capacidad) values ('GL-Class', 624);
insert into tren (modelo, capacidad) values ('850', 625);
insert into tren (modelo, capacidad) values ('Eurovan', 626);
insert into tren (modelo, capacidad) values ('Mustang', 627);
insert into tren (modelo, capacidad) values ('V70', 628);
insert into tren (modelo, capacidad) values ('RX-8', 629);
insert into tren (modelo, capacidad) values ('Matrix', 630);
insert into tren (modelo, capacidad) values ('E-Series', 631);
insert into tren (modelo, capacidad) values ('Continental', 632);
insert into tren (modelo, capacidad) values ('Lumina', 633);
insert into tren (modelo, capacidad) values ('F250', 634);
insert into tren (modelo, capacidad) values ('Park Avenue', 635);
insert into tren (modelo, capacidad) values ('9000', 636);
insert into tren (modelo, capacidad) values ('Express 1500', 637);
insert into tren (modelo, capacidad) values ('LS', 638);
insert into tren (modelo, capacidad) values ('Grand Prix', 639);
insert into tren (modelo, capacidad) values ('RX', 640);
insert into tren (modelo, capacidad) values ('911', 641);
insert into tren (modelo, capacidad) values ('Avalanche 2500', 642);
insert into tren (modelo, capacidad) values ('E-Class', 643);
insert into tren (modelo, capacidad) values ('Town & Country', 644);
insert into tren (modelo, capacidad) values ('ES', 645);
insert into tren (modelo, capacidad) values ('911', 646);
insert into tren (modelo, capacidad) values ('Q', 647);
insert into tren (modelo, capacidad) values ('CR-V', 648);
insert into tren (modelo, capacidad) values ('Taurus', 649);
insert into tren (modelo, capacidad) values ('Econoline E250', 650);
insert into tren (modelo, capacidad) values ('Altima', 651);
insert into tren (modelo, capacidad) values ('Esteem', 652);
insert into tren (modelo, capacidad) values ('2500 Club Coupe', 653);
insert into tren (modelo, capacidad) values ('Capri', 654);
insert into tren (modelo, capacidad) values ('Outlook', 655);
insert into tren (modelo, capacidad) values ('Civic Si', 656);
insert into tren (modelo, capacidad) values ('DBS', 657);
insert into tren (modelo, capacidad) values ('Suburban', 658);
insert into tren (modelo, capacidad) values ('Escort', 659);
insert into tren (modelo, capacidad) values ('900', 660);
insert into tren (modelo, capacidad) values ('CL-Class', 661);
insert into tren (modelo, capacidad) values ('xB', 662);
insert into tren (modelo, capacidad) values ('Ram', 663);
insert into tren (modelo, capacidad) values ('5 Series', 664);
insert into tren (modelo, capacidad) values ('XL-7', 665);
insert into tren (modelo, capacidad) values ('Highlander', 666);
insert into tren (modelo, capacidad) values ('Ghost', 667);
insert into tren (modelo, capacidad) values ('Rockette', 668);
insert into tren (modelo, capacidad) values ('Seville', 669);
insert into tren (modelo, capacidad) values ('MKT', 670);
insert into tren (modelo, capacidad) values ('Grand Vitara', 671);
insert into tren (modelo, capacidad) values ('Galant', 672);
insert into tren (modelo, capacidad) values ('GTO', 673);
insert into tren (modelo, capacidad) values ('QX56', 674);
insert into tren (modelo, capacidad) values ('300', 675);
insert into tren (modelo, capacidad) values ('Vandura G3500', 676);
insert into tren (modelo, capacidad) values ('Frontier', 677);
insert into tren (modelo, capacidad) values ('E150', 678);
insert into tren (modelo, capacidad) values ('W201', 679);
insert into tren (modelo, capacidad) values ('Elantra', 680);
insert into tren (modelo, capacidad) values ('Skyhawk', 681);
insert into tren (modelo, capacidad) values ('Camaro', 682);
insert into tren (modelo, capacidad) values ('Vandura 2500', 683);
insert into tren (modelo, capacidad) values ('Ram Van 3500', 684);
insert into tren (modelo, capacidad) values ('SLS AMG', 685);
insert into tren (modelo, capacidad) values ('Explorer Sport Trac', 686);
insert into tren (modelo, capacidad) values ('Mountaineer', 687);
insert into tren (modelo, capacidad) values ('PT Cruiser', 688);
insert into tren (modelo, capacidad) values ('Summit', 689);
insert into tren (modelo, capacidad) values ('4Runner', 690);
insert into tren (modelo, capacidad) values ('G-Series 1500', 691);
insert into tren (modelo, capacidad) values ('R32', 692);
insert into tren (modelo, capacidad) values ('M6', 693);
insert into tren (modelo, capacidad) values ('H2', 694);
insert into tren (modelo, capacidad) values ('Firebird', 695);
insert into tren (modelo, capacidad) values ('Trans Sport', 696);
insert into tren (modelo, capacidad) values ('Sunfire', 697);
insert into tren (modelo, capacidad) values ('Terraza', 698);
insert into tren (modelo, capacidad) values ('Express 2500', 699);
insert into tren (modelo, capacidad) values ('Voyager', 700);
insert into tren (modelo, capacidad) values ('Beretta', 701);
insert into tren (modelo, capacidad) values ('Touareg 2', 702);
insert into tren (modelo, capacidad) values ('Ascender', 703);
insert into tren (modelo, capacidad) values ('V70', 704);
insert into tren (modelo, capacidad) values ('Ram Wagon B350', 705);
insert into tren (modelo, capacidad) values ('Taurus', 706);
insert into tren (modelo, capacidad) values ('Escort', 707);
insert into tren (modelo, capacidad) values ('Santa Fe', 708);
insert into tren (modelo, capacidad) values ('B-Series', 709);
insert into tren (modelo, capacidad) values ('Aurora', 710);
insert into tren (modelo, capacidad) values ('tC', 711);
insert into tren (modelo, capacidad) values ('Town & Country', 712);
insert into tren (modelo, capacidad) values ('ES', 713);
insert into tren (modelo, capacidad) values ('Silverado', 714);
insert into tren (modelo, capacidad) values ('Touareg', 715);
insert into tren (modelo, capacidad) values ('Rabbit', 716);
insert into tren (modelo, capacidad) values ('Corvette', 717);
insert into tren (modelo, capacidad) values ('Continental Flying Spur', 718);
insert into tren (modelo, capacidad) values ('4000s', 719);
insert into tren (modelo, capacidad) values ('Tracker', 720);
insert into tren (modelo, capacidad) values ('XJ Series', 721);
insert into tren (modelo, capacidad) values ('S-Class', 722);
insert into tren (modelo, capacidad) values ('F250', 723);
insert into tren (modelo, capacidad) values ('Grand Marquis', 724);
insert into tren (modelo, capacidad) values ('323', 725);
insert into tren (modelo, capacidad) values ('Firefly', 726);
insert into tren (modelo, capacidad) values ('Insight', 727);
insert into tren (modelo, capacidad) values ('Diamante', 728);
insert into tren (modelo, capacidad) values ('Montero', 729);
insert into tren (modelo, capacidad) values ('Grand Cherokee', 730);
insert into tren (modelo, capacidad) values ('9-3', 731);
insert into tren (modelo, capacidad) values ('Grand Vitara', 732);
insert into tren (modelo, capacidad) values ('Murano', 733);
insert into tren (modelo, capacidad) values ('Datsun/Nissan Z-car', 734);
insert into tren (modelo, capacidad) values ('Expedition EL', 735);
insert into tren (modelo, capacidad) values ('Ram', 736);
insert into tren (modelo, capacidad) values ('57', 737);
insert into tren (modelo, capacidad) values ('Sebring', 738);
insert into tren (modelo, capacidad) values ('Pilot', 739);
insert into tren (modelo, capacidad) values ('F250', 740);
insert into tren (modelo, capacidad) values ('944', 741);
insert into tren (modelo, capacidad) values ('500E', 742);
insert into tren (modelo, capacidad) values ('Sable', 743);
insert into tren (modelo, capacidad) values ('Phantom', 744);
insert into tren (modelo, capacidad) values ('SLK-Class', 745);
insert into tren (modelo, capacidad) values ('Vantage', 746);
insert into tren (modelo, capacidad) values ('GLK-Class', 747);
insert into tren (modelo, capacidad) values ('Suburban 2500', 748);
insert into tren (modelo, capacidad) values ('DeVille', 749);
insert into tren (modelo, capacidad) values ('Explorer', 750);
insert into tren (modelo, capacidad) values ('Outback', 751);
insert into tren (modelo, capacidad) values ('S4', 752);
insert into tren (modelo, capacidad) values ('929', 753);
insert into tren (modelo, capacidad) values ('Firebird', 754);
insert into tren (modelo, capacidad) values ('Sonic', 755);
insert into tren (modelo, capacidad) values ('DTS', 756);
insert into tren (modelo, capacidad) values ('BRZ', 757);
insert into tren (modelo, capacidad) values ('Bonneville', 758);
insert into tren (modelo, capacidad) values ('Tracer', 759);
insert into tren (modelo, capacidad) values ('Corvette', 760);
insert into tren (modelo, capacidad) values ('SLK-Class', 761);
insert into tren (modelo, capacidad) values ('Corvette', 762);
insert into tren (modelo, capacidad) values ('Grand Marquis', 763);
insert into tren (modelo, capacidad) values ('Scirocco', 764);
insert into tren (modelo, capacidad) values ('Sequoia', 765);
insert into tren (modelo, capacidad) values ('Sorento', 766);
insert into tren (modelo, capacidad) values ('Murciélago', 767);
insert into tren (modelo, capacidad) values ('Navajo', 768);
insert into tren (modelo, capacidad) values ('Taurus', 769);
insert into tren (modelo, capacidad) values ('Sprinter 3500', 770);
insert into tren (modelo, capacidad) values ('Avenger', 771);
insert into tren (modelo, capacidad) values ('Diablo', 772);
insert into tren (modelo, capacidad) values ('Solara', 773);
insert into tren (modelo, capacidad) values ('Vandura G1500', 774);
insert into tren (modelo, capacidad) values ('S-Type', 775);
insert into tren (modelo, capacidad) values ('Accord', 776);
insert into tren (modelo, capacidad) values ('550', 777);
insert into tren (modelo, capacidad) values ('944', 778);
insert into tren (modelo, capacidad) values ('Freestar', 779);
insert into tren (modelo, capacidad) values ('Ram 1500', 780);
insert into tren (modelo, capacidad) values ('Vantage', 781);
insert into tren (modelo, capacidad) values ('Express 3500', 782);
insert into tren (modelo, capacidad) values ('Envoy', 783);
insert into tren (modelo, capacidad) values ('9000', 784);
insert into tren (modelo, capacidad) values ('SL-Class', 785);
insert into tren (modelo, capacidad) values ('Golf', 786);
insert into tren (modelo, capacidad) values ('Armada', 787);
insert into tren (modelo, capacidad) values ('Jetta', 788);
insert into tren (modelo, capacidad) values ('Durango', 789);
insert into tren (modelo, capacidad) values ('Regal', 790);
insert into tren (modelo, capacidad) values ('CR-V', 791);
insert into tren (modelo, capacidad) values ('Suburban 2500', 792);
insert into tren (modelo, capacidad) values ('Vibe', 793);
insert into tren (modelo, capacidad) values ('Legacy', 794);
insert into tren (modelo, capacidad) values ('Datsun/Nissan Z-car', 795);
insert into tren (modelo, capacidad) values ('Prizm', 796);
insert into tren (modelo, capacidad) values ('Sunfire', 797);
insert into tren (modelo, capacidad) values ('SL-Class', 798);
insert into tren (modelo, capacidad) values ('RX-8', 799);
insert into tren (modelo, capacidad) values ('Outback', 800);
insert into tren (modelo, capacidad) values ('90', 801);
insert into tren (modelo, capacidad) values ('Forester', 802);
insert into tren (modelo, capacidad) values ('G6', 803);
insert into tren (modelo, capacidad) values ('Sidekick', 804);
insert into tren (modelo, capacidad) values ('Continental Flying Spur', 805);
insert into tren (modelo, capacidad) values ('Prius v', 806);
insert into tren (modelo, capacidad) values ('SVX', 807);
insert into tren (modelo, capacidad) values ('XJ Series', 808);
insert into tren (modelo, capacidad) values ('Highlander Hybrid', 809);
insert into tren (modelo, capacidad) values ('F250', 810);
insert into tren (modelo, capacidad) values ('Karif', 811);
insert into tren (modelo, capacidad) values ('Navigator', 812);
insert into tren (modelo, capacidad) values ('SL-Class', 813);
insert into tren (modelo, capacidad) values ('Range Rover', 814);
insert into tren (modelo, capacidad) values ('PT Cruiser', 815);
insert into tren (modelo, capacidad) values ('350Z', 816);
insert into tren (modelo, capacidad) values ('Passat', 817);
insert into tren (modelo, capacidad) values ('Yaris', 818);
insert into tren (modelo, capacidad) values ('C30', 819);
insert into tren (modelo, capacidad) values ('RSX', 820);
insert into tren (modelo, capacidad) values ('Continental', 821);
insert into tren (modelo, capacidad) values ('Caravan', 822);
insert into tren (modelo, capacidad) values ('Grand Prix', 823);
insert into tren (modelo, capacidad) values ('500', 824);
insert into tren (modelo, capacidad) values ('1500', 825);
insert into tren (modelo, capacidad) values ('Suburban 2500', 826);
insert into tren (modelo, capacidad) values ('S80', 827);
insert into tren (modelo, capacidad) values ('Mini Cooper', 828);
insert into tren (modelo, capacidad) values ('Navigator', 829);
insert into tren (modelo, capacidad) values ('Elantra', 830);
insert into tren (modelo, capacidad) values ('E150', 831);
insert into tren (modelo, capacidad) values ('3500', 832);
insert into tren (modelo, capacidad) values ('Cayenne', 833);
insert into tren (modelo, capacidad) values ('Crossfire', 834);
insert into tren (modelo, capacidad) values ('LeBaron', 835);
insert into tren (modelo, capacidad) values ('Grand Vitara', 836);
insert into tren (modelo, capacidad) values ('Dynasty', 837);
insert into tren (modelo, capacidad) values ('Regal', 838);
insert into tren (modelo, capacidad) values ('F250', 839);
insert into tren (modelo, capacidad) values ('E-Class', 840);
insert into tren (modelo, capacidad) values ('A6', 841);
insert into tren (modelo, capacidad) values ('SRX', 842);
insert into tren (modelo, capacidad) values ('164', 843);
insert into tren (modelo, capacidad) values ('G-Series G10', 844);
insert into tren (modelo, capacidad) values ('S80', 845);
insert into tren (modelo, capacidad) values ('Astra', 846);
insert into tren (modelo, capacidad) values ('Forenza', 847);
insert into tren (modelo, capacidad) values ('Colorado', 848);
insert into tren (modelo, capacidad) values ('Econoline E250', 849);
insert into tren (modelo, capacidad) values ('Sentra', 850);
insert into tren (modelo, capacidad) values ('Tucson', 851);
insert into tren (modelo, capacidad) values ('Boxster', 852);
insert into tren (modelo, capacidad) values ('Aurora', 853);
insert into tren (modelo, capacidad) values ('Ram 2500 Club', 854);
insert into tren (modelo, capacidad) values ('Caravan', 855);
insert into tren (modelo, capacidad) values ('LeSabre', 856);
insert into tren (modelo, capacidad) values ('SLS-Class', 857);
insert into tren (modelo, capacidad) values ('Aurora', 858);
insert into tren (modelo, capacidad) values ('240SX', 859);
insert into tren (modelo, capacidad) values ('Seville', 860);
insert into tren (modelo, capacidad) values ('RAV4', 861);
insert into tren (modelo, capacidad) values ('G35', 862);
insert into tren (modelo, capacidad) values ('Falcon', 863);
insert into tren (modelo, capacidad) values ('Taurus', 864);
insert into tren (modelo, capacidad) values ('Sedona', 865);
insert into tren (modelo, capacidad) values ('Rabbit', 866);
insert into tren (modelo, capacidad) values ('Swift', 867);
insert into tren (modelo, capacidad) values ('M-Class', 868);
insert into tren (modelo, capacidad) values ('Malibu', 869);
insert into tren (modelo, capacidad) values ('C-Class', 870);
insert into tren (modelo, capacidad) values ('LaCrosse', 871);
insert into tren (modelo, capacidad) values ('D150 Club', 872);
insert into tren (modelo, capacidad) values ('Range Rover', 873);
insert into tren (modelo, capacidad) values ('Vigor', 874);
insert into tren (modelo, capacidad) values ('DB9 Volante', 875);
insert into tren (modelo, capacidad) values ('Regal', 876);
insert into tren (modelo, capacidad) values ('Discovery', 877);
insert into tren (modelo, capacidad) values ('6 Series', 878);
insert into tren (modelo, capacidad) values ('L300', 879);
insert into tren (modelo, capacidad) values ('Econoline E150', 880);
insert into tren (modelo, capacidad) values ('Escort', 881);
insert into tren (modelo, capacidad) values ('Mazda3', 882);
insert into tren (modelo, capacidad) values ('Econoline E350', 883);
insert into tren (modelo, capacidad) values ('Suburban 1500', 884);
insert into tren (modelo, capacidad) values ('Corvette', 885);
insert into tren (modelo, capacidad) values ('Tahoe', 886);
insert into tren (modelo, capacidad) values ('VUE', 887);
insert into tren (modelo, capacidad) values ('Passport', 888);
insert into tren (modelo, capacidad) values ('Murano', 889);
insert into tren (modelo, capacidad) values ('530', 890);
insert into tren (modelo, capacidad) values ('F-Series', 891);
insert into tren (modelo, capacidad) values ('APV', 892);
insert into tren (modelo, capacidad) values ('944', 893);
insert into tren (modelo, capacidad) values ('Hombre Space', 894);
insert into tren (modelo, capacidad) values ('VUE', 895);
insert into tren (modelo, capacidad) values ('CL-Class', 896);
insert into tren (modelo, capacidad) values ('GX', 897);
insert into tren (modelo, capacidad) values ('Veracruz', 898);
insert into tren (modelo, capacidad) values ('Mustang', 899);
insert into tren (modelo, capacidad) values ('Cougar', 900);
insert into tren (modelo, capacidad) values ('Bonneville', 901);
insert into tren (modelo, capacidad) values ('Grand Prix', 902);
insert into tren (modelo, capacidad) values ('Silverado 1500', 903);
insert into tren (modelo, capacidad) values ('Sequoia', 904);
insert into tren (modelo, capacidad) values ('612 Scaglietti', 905);
insert into tren (modelo, capacidad) values ('SL-Class', 906);
insert into tren (modelo, capacidad) values ('LX', 907);
insert into tren (modelo, capacidad) values ('Camry', 908);
insert into tren (modelo, capacidad) values ('Savana 2500', 909);
insert into tren (modelo, capacidad) values ('Crosstour', 910);
insert into tren (modelo, capacidad) values ('Yukon', 911);
insert into tren (modelo, capacidad) values ('Suburban 1500', 912);
insert into tren (modelo, capacidad) values ('Ram 1500', 913);
insert into tren (modelo, capacidad) values ('Justy', 914);
insert into tren (modelo, capacidad) values ('GL-Class', 915);
insert into tren (modelo, capacidad) values ('Bronco', 916);
insert into tren (modelo, capacidad) values ('Mustang', 917);
insert into tren (modelo, capacidad) values ('Lancer Evolution', 918);
insert into tren (modelo, capacidad) values ('Sierra 2500HD', 919);
insert into tren (modelo, capacidad) values ('Tribute', 920);
insert into tren (modelo, capacidad) values ('Impala', 921);
insert into tren (modelo, capacidad) values ('57', 922);
insert into tren (modelo, capacidad) values ('Quattroporte', 923);
insert into tren (modelo, capacidad) values ('Frontier', 924);
insert into tren (modelo, capacidad) values ('Camaro', 925);
insert into tren (modelo, capacidad) values ('Accent', 926);
insert into tren (modelo, capacidad) values ('B-Series', 927);
insert into tren (modelo, capacidad) values ('Ram 1500', 928);
insert into tren (modelo, capacidad) values ('CL-Class', 929);
insert into tren (modelo, capacidad) values ('Accord Crosstour', 930);
insert into tren (modelo, capacidad) values ('Sierra 2500', 931);
insert into tren (modelo, capacidad) values ('300CE', 932);
insert into tren (modelo, capacidad) values ('Mark VIII', 933);
insert into tren (modelo, capacidad) values ('V50', 934);
insert into tren (modelo, capacidad) values ('Lancer Evolution', 935);
insert into tren (modelo, capacidad) values ('Pathfinder', 936);
insert into tren (modelo, capacidad) values ('LS Hybrid', 937);
insert into tren (modelo, capacidad) values ('C70', 938);
insert into tren (modelo, capacidad) values ('3000GT', 939);
insert into tren (modelo, capacidad) values ('MR2', 940);
insert into tren (modelo, capacidad) values ('Vibe', 941);
insert into tren (modelo, capacidad) values ('88', 942);
insert into tren (modelo, capacidad) values ('S4', 943);
insert into tren (modelo, capacidad) values ('Milan', 944);
insert into tren (modelo, capacidad) values ('Voyager', 945);
insert into tren (modelo, capacidad) values ('Sorento', 946);
insert into tren (modelo, capacidad) values ('3 Series', 947);
insert into tren (modelo, capacidad) values ('Continental Super', 948);
insert into tren (modelo, capacidad) values ('SL-Class', 949);
insert into tren (modelo, capacidad) values ('Continental Mark VII', 950);
insert into tren (modelo, capacidad) values ('Malibu', 951);
insert into tren (modelo, capacidad) values ('Fleetwood', 952);
insert into tren (modelo, capacidad) values ('Corolla', 953);
insert into tren (modelo, capacidad) values ('Mountaineer', 954);
insert into tren (modelo, capacidad) values ('Regal', 955);
insert into tren (modelo, capacidad) values ('Park Avenue', 956);
insert into tren (modelo, capacidad) values ('GX', 957);
insert into tren (modelo, capacidad) values ('Golf', 958);
insert into tren (modelo, capacidad) values ('LS', 959);
insert into tren (modelo, capacidad) values ('9-5', 960);
insert into tren (modelo, capacidad) values ('Envoy', 961);
insert into tren (modelo, capacidad) values ('SC', 962);
insert into tren (modelo, capacidad) values ('Monte Carlo', 963);
insert into tren (modelo, capacidad) values ('Crown Victoria', 964);
insert into tren (modelo, capacidad) values ('XT', 965);
insert into tren (modelo, capacidad) values ('GTI', 966);
insert into tren (modelo, capacidad) values ('Milan', 967);
insert into tren (modelo, capacidad) values ('Q', 968);
insert into tren (modelo, capacidad) values ('Freelander', 969);
insert into tren (modelo, capacidad) values ('Range Rover', 970);
insert into tren (modelo, capacidad) values ('Sierra 2500', 971);
insert into tren (modelo, capacidad) values ('Sable', 972);
insert into tren (modelo, capacidad) values ('MKT', 973);
insert into tren (modelo, capacidad) values ('RX-7', 974);
insert into tren (modelo, capacidad) values ('SL-Class', 975);
insert into tren (modelo, capacidad) values ('Eos', 976);
insert into tren (modelo, capacidad) values ('Corolla', 977);
insert into tren (modelo, capacidad) values ('Mariner', 978);
insert into tren (modelo, capacidad) values ('Eclipse', 979);
insert into tren (modelo, capacidad) values ('Brat', 980);
insert into tren (modelo, capacidad) values ('Gran Sport', 981);
insert into tren (modelo, capacidad) values ('4Runner', 982);
insert into tren (modelo, capacidad) values ('Aveo', 983);
insert into tren (modelo, capacidad) values ('Truck', 984);
insert into tren (modelo, capacidad) values ('3500', 985);
insert into tren (modelo, capacidad) values ('Celica', 986);
insert into tren (modelo, capacidad) values ('Riviera', 987);
insert into tren (modelo, capacidad) values ('V70', 988);
insert into tren (modelo, capacidad) values ('Grand Voyager', 989);
insert into tren (modelo, capacidad) values ('RS4', 990);
insert into tren (modelo, capacidad) values ('LS', 991);
insert into tren (modelo, capacidad) values ('Impulse', 992);
insert into tren (modelo, capacidad) values ('I', 993);
insert into tren (modelo, capacidad) values ('Grand Prix', 994);
insert into tren (modelo, capacidad) values ('X3', 995);
insert into tren (modelo, capacidad) values ('Topaz', 996);
insert into tren (modelo, capacidad) values ('900', 997);
insert into tren (modelo, capacidad) values ('Sportage', 998);
insert into tren (modelo, capacidad) values ('Discovery Series II', 999);
insert into tren (modelo, capacidad) values ('9000', 1000);
